### ISSUE TITLE
1.19.3无法启动

### ISSUE THREAD

**Issue by zyjawa** [Hex-Dragon/PCL2#1061]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.19.3的forge版本无法进入，mod全部关闭仍然无法打开

### 错误报告、日志与附件

[错误报告-2023-1-29_8.52.21.zip](https://github.com/Hex-Dragon/PCL2/files/10528688/-2023-1-29_8.52.21.zip)

**Comment by youzi-2333** [comment]
PCL2 提供信息：
```
[08:35:02.588] 没有对文件夹 E:\GTA5\ 的权限，请尝试以管理员权限运行 PCL：对路径“E:\GTA5\CheckPermission46”的访问被拒绝。
PCL2 的权限不足。请尝试右键 PCL2，选择以管理员身份运行。
————————————
详细错误信息：
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 PCL.ModBase.CheckPermission(String Path)
错误类型：System.UnauthorizedAccessException
```
请尝试以管理员身份重启 PCL2 再试？

不过我对此环境进行了模拟，未能复现。

**Comment by youzi-2333** [comment]
也可能是 Optifine 与 Forge 不兼容导致的，把 Optifine 删掉试试？

**Comment by zyjawa** [comment]
在mod里面把optifine禁了，还是闪退。。。




Jason
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月29日(星期天) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 1.19.3无法启动 (Issue #1061)





 
也可能是 Optifine 与 Forge 不兼容导致的，把 Optifine 删掉试试？

**Comment by FangFuJi1991** [comment]
> PCL2 提供信息：
> 
> ```
> [08:35:02.588] 没有对文件夹 E:\GTA5\ 的权限，请尝试以管理员权限运行 PCL：对路径“E:\GTA5\CheckPermission46”的访问被拒绝。
> PCL2 的权限不足。请尝试右键 PCL2，选择以管理员身份运行。
> ————————————
> 详细错误信息：
>    在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>    在 PCL.ModBase.CheckPermission(String Path)
> 错误类型：System.UnauthorizedAccessException
> ```
> 
> 请尝试以管理员身份重启 PCL2 再试？
> 
> 不过我对此环境进行了模拟，未能复现。

gta5文件夹？

**Comment by zyjawa** [comment]
我好像没有把pcl放进GTA5啊，反正我再试一下






Jason
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月29日(星期天) 中午1:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 1.19.3无法启动 (Issue #1061)





  
PCL2 提供信息：
 [08:35:02.588] 没有对文件夹 E:\GTA5\ 的权限，请尝试以管理员权限运行 PCL：对路径“E:\GTA5\CheckPermission46”的访问被拒绝。 PCL2 的权限不足。请尝试右键 PCL2，选择以管理员身份运行。 ———————————— 详细错误信息：    在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)    在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)    在 PCL.ModBase.CheckPermission(String Path) 错误类型：System.UnauthorizedAccessException  
请尝试以管理员身份重启 PCL2 再试？
 
不过我对此环境进行了模拟，未能复现。
  
gta5文件夹？

**Comment by youzi-2333** [comment]
我也不知道 PCL 为啥要测 `GTA5` 文件夹的权限……GTA5 不是 Minecraft 目录吧……

**Comment by youzi-2333** [comment]
<details>
<summary>latest.log 报错信息</summary>
<code>[291月2023 08:52:16.814] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: 'void net.minecraft.client.renderer.texture.SpriteContents.<init>(net.minecraft.resources.ResourceLocation, net.minecraft.client.resources.metadata.animation.FrameSize, com.mojang.blaze3d.platform.NativeImage, net.minecraft.client.resources.metadata.animation.AnimationMetadataSection, net.minecraftforge.client.textures.ForgeTextureMetadata)'
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class net.minecraftforge.client.ClientForgeMod onRegisterGeometryLoaders(Lnet/minecraftforge/client/event/ModelEvent$RegisterGeometryLoaders;)V
java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.texture.SpriteContents.<init>(net.minecraft.resources.ResourceLocation, net.minecraft.client.resources.metadata.animation.FrameSize, com.mojang.blaze3d.platform.NativeImage, net.minecraft.client.resources.metadata.animation.AnimationMetadataSection, net.minecraftforge.client.textures.ForgeTextureMetadata)'
	at TRANSFORMER/forge@44.1.0/net.minecraftforge.client.textures.UnitTextureAtlasSprite.<init>(UnitTextureAtlasSprite.java:28)
	at TRANSFORMER/forge@44.1.0/net.minecraftforge.client.textures.UnitTextureAtlasSprite.<clinit>(UnitTextureAtlasSprite.java:24)
	at TRANSFORMER/forge@44.1.0/net.minecraftforge.client.model.EmptyModel$Baked.<init>(EmptyModel.java:66)
	at TRANSFORMER/forge@44.1.0/net.minecraftforge.client.model.EmptyModel.<clinit>(EmptyModel.java:40)
	at TRANSFORMER/forge@44.1.0/net.minecraftforge.client.ClientForgeMod.onRegisterGeometryLoaders(ClientForgeMod.java:29)
	at TRANSFORMER/forge@44.1.0/net.minecraftforge.client.__ClientForgeMod_onRegisterGeometryLoaders_RegisterGeometryLoaders.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.19.3-44.1.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.0/net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$36(ModLoader.java:329)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.0/net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:225)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.0/net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:327)
	at TRANSFORMER/forge@44.1.0/net.minecraftforge.client.model.geometry.GeometryLoaderManager.init(GeometryLoaderManager.java:53)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.client.resources.model.ModelManager.m_5540_(ModelManager.java:79)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.packs.resources.SimpleReloadInstance.m_10827_(SimpleReloadInstance.java:32)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.packs.resources.SimpleReloadInstance.<init>(SimpleReloadInstance.java:44)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.packs.resources.SimpleReloadInstance.m_10815_(SimpleReloadInstance.java:32)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.packs.resources.SimpleReloadInstance.m_203834_(SimpleReloadInstance.java:101)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:45)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.client.Minecraft.<init>(Minecraft.java:580)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.client.main.Main.m_239872_(Main.java:176)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.3-44.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

[291月2023 08:52:16.816] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event net.minecraftforge.client.event.ModelEvent$RegisterGeometryLoaders@125124ea dispatch for modid forge
java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.texture.SpriteContents.<init>(net.minecraft.resources.ResourceLocation, net.minecraft.client.resources.metadata.animation.FrameSize, com.mojang.blaze3d.platform.NativeImage, net.minecraft.client.resources.metadata.animation.AnimationMetadataSection, net.minecraftforge.client.textures.ForgeTextureMetadata)'
	at net.minecraftforge.client.textures.UnitTextureAtlasSprite.<init>(UnitTextureAtlasSprite.java:28) ~[forge-1.19.3-44.1.0-universal.jar%23155!/:?]
	at net.minecraftforge.client.textures.UnitTextureAtlasSprite.<clinit>(UnitTextureAtlasSprite.java:24) ~[forge-1.19.3-44.1.0-universal.jar%23155!/:?]
	at net.minecraftforge.client.model.EmptyModel$Baked.<init>(EmptyModel.java:66) ~[forge-1.19.3-44.1.0-universal.jar%23155!/:?]
	at net.minecraftforge.client.model.EmptyModel.<clinit>(EmptyModel.java:40) ~[forge-1.19.3-44.1.0-universal.jar%23155!/:?]
	at net.minecraftforge.client.ClientForgeMod.onRegisterGeometryLoaders(ClientForgeMod.java:29) ~[forge-1.19.3-44.1.0-universal.jar%23155!/:?]
	at net.minecraftforge.client.__ClientForgeMod_onRegisterGeometryLoaders_RegisterGeometryLoaders.invoke(.dynamic) ~[forge-1.19.3-44.1.0-universal.jar%23155!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%23131!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23131!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23131!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.3-44.1.0.jar%23152!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$36(ModLoader.java:329) ~[fmlcore-1.19.3-44.1.0.jar%23151!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:225) ~[fmlcore-1.19.3-44.1.0.jar%23151!/:?]
	at net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:327) ~[fmlcore-1.19.3-44.1.0.jar%23151!/:?]
	at net.minecraftforge.client.model.geometry.GeometryLoaderManager.init(GeometryLoaderManager.java:53) ~[forge-1.19.3-44.1.0-universal.jar%23155!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5540_(ModelManager.java:79) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10827_(SimpleReloadInstance.java:32) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.<init>(SimpleReloadInstance.java:44) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10815_(SimpleReloadInstance.java:32) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_203834_(SimpleReloadInstance.java:101) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:45) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:580) ~[client-1.19.3-20221207.122022-srg.jar%23150!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[1.19.3-Forge_44.1.0-OptiFine_I2_pre2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-Forge_44.1.0-OptiFine_I2_pre2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]</code>
</details>

怀疑两个报错本质相同，一个是在触发 Event 的时候出了问题，一个是在 Event 中出了 Exception，先等龙猫看看吧.gif

**Comment by LTCatt** [comment]
`Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.texture.SpriteContents.<init>`

怀疑 MC JAR 文件损坏……重新下一下这个版本。
如果其他启动器能启动，附带导出的启动脚本……

**Comment by WForst-Breeze** [comment]
请反馈者尽快完成信息补充，否则此反馈将会被超时关闭🙁

**Comment by LTCatt** [comment]
超时关闭，若有需要可以继续回复
