### ISSUE TITLE
1.12.2的我的世界forge版本无法启动

### ISSUE THREAD

**Issue by 12jskajh123** [Hex-Dragon/PCL2#1277]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

进入游戏后就黑屏，然后退出游戏，其他游戏没有异常

### 错误报告、日志与附件

[错误报告-2023-2-14_星期二_19.29.03.zip](https://github.com/Hex-Dragon/PCL2/files/10743207/-2023-2-14_._19.29.03.zip)

**Comment by iPodtouch6557** [comment]
对我来说都是hmcl的问题了（
我没这个问题，应该和你有关

**Comment by youzi-2333** [comment]
您好，
根据崩溃报告，似乎添加了 Pixelmon Mod，请再次确认是否添加了 Mod，感谢配合。

**Comment by 12jskajh123** [comment]
没添加的时候也会崩溃退出，有尝试过了，没forge的1.12.2的我的世界不会崩溃



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 1.12.2的我的世界forge版本无法启动 (Issue #1277)




 
您好，
 根据崩溃报告，似乎添加了 Pixelmon Mod，请再次确认是否添加了 Mod，感谢配合。

**Comment by youzi-2333** [comment]
那就把 Mod 禁用之后再传一遍崩溃报告（）

**Comment by youzi-2333** [comment]
找到个一模一样的报错，[这里](https://www.mcbbs.net/thread-969549-1-1.html) 更新 Java 似乎能解决……？
算了先等等龙猫吧.exe

**Comment by 12jskajh123** [comment]
烈火神魔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 1.12.2的我的世界forge版本无法启动 (Issue #1277)





 
那就把 Mod 禁用之后再传一遍崩溃报告（）
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

错误报告-2023-2-17_星期五_13.23.54.zip (31.1K, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=6d326139acb0c7cb54e13c9b12330a1b4e465900560a0c071b56075b521e090202004c5a040b0d195350540906035e0d010a595d34153880dbfc92889c8bde190402530a19011505016db1fef2e9f6d16903521706001601021c1b50443305&t=exs_ftn_download&code=62a94384

**Comment by youzi-2333** [comment]
？什么意思（）

**Comment by 12jskajh123** [comment]
关了mod的崩溃报告



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月18日(周六) 晚上6:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 1.12.2的我的世界forge版本无法启动 (Issue #1277)




 
？什么意思（）

**Comment by 12jskajh123** [comment]
> 参见 #1174 ，重装 Java 能解决吗

不能

**Comment by youzi-2333** [comment]
主要是它没有 InnerException，就挺烦的……
不过崩溃报告有几个可疑点：
```
[19:28:24] [Thread-3/ERROR] [FML]: Splash thread Exception
java.lang.IllegalStateException: Texture creation: Invalid enum
	at net.minecraftforge.fml.client.SplashProgress.checkGLError(SplashProgress.java:937) ~[SplashProgress.class:?]
	at net.minecraftforge.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:803) ~[SplashProgress$Texture.class:?]
	at net.minecraftforge.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:753) ~[SplashProgress$Texture.class:?]
	at net.minecraftforge.fml.client.SplashProgress$2.run(SplashProgress.java:255) ~[SplashProgress$2.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[19:28:24] [Client thread/INFO] [FML]: Replaced 1036 ore ingredients
[19:28:24] [Client thread/INFO] [FML]: Searching D:\GAME\wdsj\.minecraft\versions\1.12.2-Forge_14.23.5.2829\mods for mods
[19:28:25] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[19:28:26] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod pixelmon (Pixelmon) requires [forge@[14.23.5.2860,)]
```
估计是前面这个 `java.lang.IllegalStateException: Texture creation: Invalid enum` 造成的问题……
这样说的话，其实不是 PCL2 造成的……
请确认别的启动器是否会出现问题 QwQ 感谢配合

**Comment by 12jskajh123** [comment]
别的启动器不会，用了hcml测试过了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月19日(周日) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 1.12.2的我的世界forge版本无法启动 (Issue #1277)




 
主要是它没有 InnerException，就挺烦的……
 不过崩溃报告有几个可疑点：
 [19:28:24] [Thread-3/ERROR] [FML]: Splash thread Exception java.lang.IllegalStateException: Texture creation: Invalid enum 	at net.minecraftforge.fml.client.SplashProgress.checkGLError(SplashProgress.java:937) ~[SplashProgress.class:?] 	at net.minecraftforge.fml.client.SplashProgress$Texture.<init&gt;(SplashProgress.java:803) ~[SplashProgress$Texture.class:?] 	at net.minecraftforge.fml.client.SplashProgress$Texture.<init&gt;(SplashProgress.java:753) ~[SplashProgress$Texture.class:?] 	at net.minecraftforge.fml.client.SplashProgress$2.run(SplashProgress.java:255) ~[SplashProgress$2.class:?] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131] [19:28:24] [Client thread/INFO] [FML]: Replaced 1036 ore ingredients [19:28:24] [Client thread/INFO] [FML]: Searching D:\GAME\wdsj\.minecraft\versions\1.12.2-Forge_14.23.5.2829\mods for mods [19:28:25] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load [19:28:26] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod pixelmon (Pixelmon) requires ***@***.***,)]  
估计是前面这个 java.lang.IllegalStateException: Texture creation: Invalid enum 造成的问题……
 这样说的话，其实不是 PCL2 造成的……
 请确认别的启动器是否会出现问题 QwQ 感谢配合

**Comment by youzi-2333** [comment]
好的了解了，抱歉问了这么多问题（）

@LTCatt 麻烦处理一下……

**Comment by 12jskajh123** [comment]
没事，都是为了更好解决问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月20日(周一) 晚上8:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hex-Dragon/PCL2] 1.12.2的我的世界forge版本无法启动 (Issue #1277)




 
好的了解了，抱歉问了这么多问题（）
 
@LTCatt 麻烦处理一下……

**Comment by LTCatt** [comment]
[19:28:26] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod pixelmon (Pixelmon) requires [forge@[14.23.5.2860,)]
[19:28:26] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod pixelmon (Pixelmon) requires [forge@[14.23.5.2860,)]

Pixelmon 需要 Forge 版本最低为 14.23.5.2860，但当前 Forge 版本为 14.23.5.2829。
PCL 识别的崩溃原因没有问题。

**Comment by 12jskajh123** [comment]
问题是我在pcl下载的最新版本，也就是14.23.5.2860&nbsp;


烈火神魔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月21日(星期二) 凌晨4:09
收件人: "Hex-Dragon/PCL2";
抄送: "Author";
主题: Re: [Hex-Dragon/PCL2] 1.12.2的我的世界forge版本无法启动 (Issue #1277)





 
[19:28:26] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod pixelmon (Pixelmon) requires ***@***.***,)]
 [19:28:26] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
 net.minecraftforge.fml.common.MissingModsException: Mod pixelmon (Pixelmon) requires ***@***.***,)]
 
Pixelmon 需要 Forge 版本最低为 14.23.5.2860，但当前 Forge 版本为 14.23.5.2829。
 PCL 识别的崩溃原因没有问题。
 
&mdash;

**Comment by 12jskajh123** [comment]
还有现在1.12，1.12.1,1.12.2有加forge就没办法进游戏，直接就启动错误&nbsp;


烈火神魔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月21日(星期二) 凌晨4:09
收件人: "Hex-Dragon/PCL2";
抄送: "Author";
主题: Re: [Hex-Dragon/PCL2] 1.12.2的我的世界forge版本无法启动 (Issue #1277)





 
[19:28:26] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod pixelmon (Pixelmon) requires ***@***.***,)]
 [19:28:26] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
 net.minecraftforge.fml.common.MissingModsException: Mod pixelmon (Pixelmon) requires ***@***.***,)]
 
Pixelmon 需要 Forge 版本最低为 14.23.5.2860，但当前 Forge 版本为 14.23.5.2829。
 PCL 识别的崩溃原因没有问题。
 
&mdash;
