### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by KSzihao** [Hex-Dragon/PCL2#1407]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

任何一种我的世界有mod或者无mod都打不开

### 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/10892132/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/10892133/Log2.txt)

**Comment by Chiloven945** [comment]
没log4j的配置文件，你等等Collaborator~~因为我也不知道是不是PCL问题（~~
```[15:48:57] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_351]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[?:1.8.0_351]
	at java.lang.System.loadLibrary(Unknown Source) ~[?:1.8.0_351]
	at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_351]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:87) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2984) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:38) ~[Main.class:?]
	... 12 more```

**Comment by WorldHim** [comment]
游戏崩溃一般不是启动器问题。。。

**Comment by WForst-Breeze** [comment]
自反馈提交日算起，您未能在8天内完成信息补充。请您在一周内尽快完成上述信息补充，否则此反馈将会被关闭，感谢您的支持和理解~
