### ISSUE TITLE
启动游戏蓝屏，报错，死机以及新下载的版本文件不齐全等问题

### ISSUE THREAD

**Issue by lazy-11g** [Hex-Dragon/PCL2#1730]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

前段时间启动器还用的好好的，然后突然有一天启动游戏电脑直接蓝屏了（暂时没有发现电脑硬件出现问题，电脑在日常使用和玩其他游戏时都没有出现过蓝屏或者死机的问题，只有在玩mine craft时才有这种情况）
蓝屏的版本主要是1.18以上的版本，我把从1.18.2到1.19.4的所有版本都试了个遍了都普遍存在这个问题，没有安装任何模组，有的版本是刚从启动器里面下载的，有的是以前一直在玩的，但结果都是要么启动直接蓝屏，或者是报错，有的是能进入游戏主界面但是进入任意一个存档后直接蓝屏。低版本暂时没遇到这种问题。
还有一种情况是我以前一直在玩的一个1.16.5的整合包，之前还一直没有任何问题的，我也没有对游戏文件做过任何更改，后来某一天启动之后就突然报错了。
以及新下载好的版本，版本文件夹里面的文件好像都不齐全，只有

### 错误报告、日志与附件

[错误报告-28-04-2023_11.35.56_pm(1.16.5整合包报错）.zip](https://github.com/Hex-Dragon/PCL2/files/11355487/-28-04-2023_11.35.56_pm.1.16.5.zip)
[错误报告-28-04-2023_11.40.52_pm（新下载的版本第一次启动报错）.zip](https://github.com/Hex-Dragon/PCL2/files/11355488/-28-04-2023_11.40.52_pm.zip)
![QQ截图20230429002459](https://user-images.githubusercontent.com/132079060/235202210-d77200a7-e5ad-4472-97cb-87d0ae060936.png)

**Comment by Chiloven945** [comment]
文件是完全齐全的，部分资源文件会储存在\.minecraft\assets内，其余均在游戏的jar包里

```
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Exception in thread "main" java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:55)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
```
```
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
[23:35:44] [main/INFO]: ModLauncher running: args [--username, TurfyDiagram478, --version, 1.16.5forge, --gameDir, C:\妗岄潰\PCL\.minecraft, --assetsDir, C:\妗岄潰\PCL\.minecraft\assets, --assetIndex, 1.16, --uuid, 503a812697b34f3cb728b9dd0a6344aa, --accessToken, 鉂勨潉鉂勨潉鉂勨潉鉂勨潉, --userType, Mojang, --versionType, PCL2, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion,
20210115.111550, --tweakClass, optifine.OptiFineForgeTweaker]
[23:35:44] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 18.0.1.1 by Oracle Corporation
[23:35:44] [main/INFO]: OptiFineTransformationService.onLoad
[23:35:44] [main/INFO]: OptiFine ZIP file: C:\妗岄潰\PCL\.minecraft\libraries\optifine\OptiFine\1.16.5_HD_U_G8\OptiFine-1.16.5_HD_U_G8.jar
[23:35:44] [main/INFO]: Target.PRE_CLASS is available
[23:35:44] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[23:35:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/妗岄潰/PCL/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[23:35:44] [main/INFO]: OptiFineTransformationService.initialize
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1078]: java.lang.reflect.InvocationTargetException
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1078]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1078]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1078]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1078]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: Caused by: java.lang.RuntimeException: Failed to load FML config from C:\妗岄潰\PCL\.minecraft\config\fml.toml
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:50)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at net.minecraftforge.fml.loading.FMLConfig.load(FMLConfig.java:63)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:67)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[23:35:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1087]: 	... 3 more
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.file.AutoreloadFileConfig.load(AutoreloadFileConfig.java:41)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	at net.minecraftforge.fml.loading.FMLConfig.loadFrom(FMLConfig.java:46)
[23:35:44] [main/INFO]: [java.lang.Throwable:printStackTrace:658]: 	... 13 more
Exception in thread "main" 
```
似乎是utf8编码造成的崩溃，建议尝试删除路径中的中文字符或者按着这个链接的教程进行操作
https://www.bilibili.com/read/cv17560079

**Comment by LTCatt** [comment]
PCL 不会导致蓝屏，严重怀疑为系统问题，暂不处理
