### ISSUE TITLE
Crash: 1.12.2 OptiFine G5

### ISSUE THREAD

**Issue by bwtx2022** [Hex-Dragon/PCL2#174]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

该核心由 BakaXL 创建，但 PCL2 似乎不能正确打开它，并且似乎使用了我没有添加 Path 的 Java 16。

### 错误报告、日志与附件

[错误报告-2022-10-1_下午_12.42.31.zip](https://github.com/Hex-Dragon/PCL2/files/9689553/-2022-10-1_._12.42.31.zip)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9689559/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/9689555/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/9689556/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/9689557/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/9689558/Log5.txt)

**Comment by Big-Cake-jpg** [comment]
PCL2 安装带加载器的核心时似乎不会直接创建原版核心

所以这可能是核心安装的规范性问题导致的

**Comment by bwtx2022** [comment]
PCL2 是不是和 Zulu JDK 的兼容性不太好...

我用 PCL2 安装了一个配置相同的核心，且手动指定了 Zulu JDK 8 也报错

**Comment by Big-Cake-jpg** [comment]
> PCL2 是不是和 Zulu JDK 的兼容性不太好...
> 
> 我用 PCL2 安装了一个配置相同的核心，且手动指定了 Zulu JDK 8 也报错

有试过 Oracle Java 8 或者 OpenJDK 吗

**Comment by bwtx2022** [comment]
> 

这个还没测试，等下试试看 Bellsoft 发行版

**Comment by bwtx2022** [comment]
Bellsoft 8u345 依然无法运行

**Comment by Big-Cake-jpg** [comment]
> Bellsoft 8u345 依然无法运行

既然如此，应该是核心安装规范性导致的问题。

**Comment by bwtx2022** [comment]
> > Bellsoft 8u345 依然无法运行
> 
> 既然如此，应该是核心安装规范性导致的问题。

问题是这个是 PCL2 自己安装的核心

**Comment by Big-Cake-jpg** [comment]
> > > Bellsoft 8u345 依然无法运行
> > 
> > 
> > 既然如此，应该是核心安装规范性导致的问题。
> 
> 问题是这个是 PCL2 自己安装的核心

那就换原版 Java 8 再尝试复现一次

**Comment by bwtx2022** [comment]
目前排查到我自己定义了一个 UseZGC 的 JVM 参数可能导致了问题（雾）

但恢复成默认的 UseG1GC 问题依然无法解决

**Comment by bwtx2022** [comment]
[错误报告-2022-10-1_下午_1.01.54.zip](https://github.com/Hex-Dragon/PCL2/files/9689583/-2022-10-1_._1.01.54.zip)

附上最新报告

**Comment by Big-Cake-jpg** [comment]
```
[13:01:51] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[13:01:51] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: optifine.OptiFineTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_345]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_345]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_345]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_345]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_345]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_345]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_345]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_345]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_345]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_345]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
```
这个日志咋这么短......

**Comment by xuzhichang** [comment]
at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
我觉得JavaWrapper.jar这个文件蛮可疑的

**Comment by LTCatt** [comment]
发一下版本文件夹（
/versions/版本名/

**Comment by bwtx2022** [comment]
[versions.zip](https://github.com/Hex-Dragon/PCL2/files/9790871/versions.zip)

@LTCatt 带 PCL2 命名的是 PCL2 自己创建的核心，另一个是 BakaXL 创建的核心

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/198363983-4aa0fa1d-e474-48c1-bed4-8ab86bf3efb2.png)

但你上传的 `1.12.2-OptiFine_G5-PCL2` 我可以正常启动……
如果你启动这个版本失败了，再补一个错误报告。

**Comment by LTCatt** [comment]
超时关闭。

**Comment by bwtx2022** [comment]
我改天有时间了再复现一下吧...
