### ISSUE TITLE
1.20.1第三方登录服务器出现无效的个人信息公钥签名

### ISSUE THREAD

**Issue by TaylorEevee** [Hex-Dragon/PCL2#2109]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

最新版本直接登录服务器就会出现，服务器里提示
Failed to verify Services signature
java.security.SignatureException: Signature length not correct: got 1 but was expecting 512
        at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:213) ~[?:?]
        at java.security.Signature$Delegate.engineVerify(Signature.java:1435) ~[?:?]
        at java.security.Signature.verify(Signature.java:789) ~[?:?]
        at net.minecraft.util.SignatureValidator.verifySignature(SignatureValidator.java:30) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.SignatureValidator.lambda$from$3(SignatureValidator.java:54) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at net.minecraft.util.SignatureValidator.from(SignatureValidator.java:50) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.SignatureValidator.validate(SignatureValidator.java:23) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.world.entity.player.ProfilePublicKey$Data.validateSignature(ProfilePublicKey.java:56) ~[?:?]
        at net.minecraft.world.entity.player.ProfilePublicKey.createValidated(ProfilePublicKey.java:28) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.network.chat.RemoteChatSession$Data.validate(RemoteChatSession.java:38) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatSessionUpdate(ServerGamePacketListenerImpl.java:3722) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.handle(ServerboundChatSessionUpdatePacket.java:19) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.a(ServerboundChatSessionUpdatePacket.java:9) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:27:24 ERROR]: Failed to verify Services signature
java.security.SignatureException: Signature length not correct: got 1 but was expecting 512
        at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:213) ~[?:?]
        at java.security.Signature$Delegate.engineVerify(Signature.java:1435) ~[?:?]
        at java.security.Signature.verify(Signature.java:789) ~[?:?]
        at net.minecraft.util.SignatureValidator.verifySignature(SignatureValidator.java:30) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.SignatureValidator.lambda$from$3(SignatureValidator.java:54) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at net.minecraft.util.SignatureValidator.from(SignatureValidator.java:50) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.SignatureValidator.validate(SignatureValidator.java:23) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.world.entity.player.ProfilePublicKey$Data.validateSignature(ProfilePublicKey.java:56) ~[?:?]
        at net.minecraft.world.entity.player.ProfilePublicKey.createValidated(ProfilePublicKey.java:28) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.network.chat.RemoteChatSession$Data.validate(RemoteChatSession.java:38) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatSessionUpdate(ServerGamePacketListenerImpl.java:3722) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.handle(ServerboundChatSessionUpdatePacket.java:19) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.network.protocol.game.ServerboundChatSessionUpdatePacket.a(ServerboundChatSessionUpdatePacket.java:9) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2001]

服务端使用multilogin做验证，并且enforce-secure-profile=false
最搞的是有时好的有时就不行了，再者就是旧版pcl2，我用的2.3.0版本就不会出现此问题，然后我尝试换成其他启动器(BakaXL)，也没有出现问题

### 重现步骤

1、使用blessing skin登录进游戏
2、进入使用了multilogin的服务器

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11856852/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11856853/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11856854/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11856855/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11856856/Log2.txt)

**Comment by LTCatt** [comment]
这不是启动器导致的问题 :/
