### ISSUE TITLE
在启动1.12.2Forge时无法识别到JRE8

### ISSUE THREAD

**Issue by MINECRAFTGUIYU** [Hex-Dragon/PCL2#2194]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我已确定安装了JRE8，但在启动Minecraft Forge 14.23.5.2860“自动选择合适的java”并没有搜索到JRE8，需要手动修改

### 重现步骤

启动Minecraft 1.12.2Forge
跳出“游戏似乎因为JDK或Java版本过高而崩溃了”
（可能只有我这样）

### 日志与附件

[00:17:46.141] [Launch] [全局] 出现运行中的 Minecraft
[00:17:46.377] [Launch] [12860] 日志 1/5：已出现日志输出
[00:17:46.613] [Launch] [12860] Minecraft 已退出，返回值：1
[00:17:46.614] [Launch] [12860] Minecraft 尚未加载完成，可能已崩溃
[00:17:46.614] [Launch] [全局] 已无运行中的 Minecraft
[00:17:46.614] [Launch] [12860] Minecraft 已崩溃，将在 2 秒后开始崩溃分析
[00:17:46.691] 加载线程 等待游戏窗口出现 (116) 发生运行时错误：$$
   在 PCL.ModLaunch.McLaunchWait(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
[00:17:46.691] [Loader] 加载器 等待游戏窗口出现 状态改变：Failed
[00:17:46.691] [Loader] 加载器 Minecraft 启动 状态改变：Failed
[00:17:46.693] [UI] 弹出提示：检测到 Minecraft 出现错误，错误分析已开始……
[00:17:46.847] [Launch] [12860] Minecraft 日志监控已退出
[00:17:46.925] 加载线程 Loader Launch (111) 发生运行时错误：等待游戏窗口出现失败
→ $$
   在 PCL.ModLaunch.McLaunchStart(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModLaunch.McLaunchWait(LoaderTask`2 Loader)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
[00:17:46.926] [Loader] 加载器 Loader Launch 状态改变：Failed
[00:17:48.623] [Launch] [12860] 崩溃分析开始
[00:17:48.628] [Crash] 崩溃分析暂存文件夹：C:\Users\Administrator\AppData\Local\Temp\PCL\CrashAnalyzer\1286076800813\
[00:17:48.628] [Crash] 步骤 1：收集日志文件
[00:17:48.629] [Crash] 未发现可能可用的日志文件
[00:17:48.629] [Crash] 以下为游戏输出的最后一段内容：
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
jlw: native file exists: 'C:\Users\Administrator\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
[00:17:48.631] [Crash] 步骤 1：收集日志文件完成，收集到 1 个文件
[00:17:48.631] [Crash] 步骤 2：准备日志文本
[00:17:48.631] [Crash] rawoutput.log 分类为 MinecraftLog
[00:17:48.631] [Crash] 输出报告：C:\Users\Administrator\AppData\Local\Temp\PCL\CrashAnalyzer\1286076800813\RawOutput.log，作为 Minecraft 或启动器日志
[00:17:48.631] [Crash] 导入分析：C:\Users\Administrator\AppData\Local\Temp\PCL\CrashAnalyzer\1286076800813\RawOutput.log，作为启动器日志
[00:17:48.631] [Crash] 步骤 2：准备日志文本完成，找到游戏日志用作分析
[00:17:48.631] [Crash] 步骤 3：分析崩溃原因
[00:17:48.631] [Crash] 可能的崩溃原因：使用JDK
[00:17:48.631] [Crash] 步骤 3：分析崩溃原因完成，找到 1 条可能的原因
[00:17:48.631] [Crash]  - 使用JDK
[00:17:48.712] [System] 窗口已置顶，位置：(395, 102), 1005 x 470
[00:17:48.730] [Control] 普通弹窗：Minecraft 出现错误
游戏似乎因为使用 JDK，或 Java 版本过高而崩溃了。
请在启动设置的 Java 选择一项中改用 JRE 8（Java 8），然后再启动游戏。
如果你没有安装 JRE 8，你可以从网络中下载、安装一个。

错误日志

WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
jlw: native file exists: 'C:\Users\Administrator\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more

**Comment by bwtx2023** [comment]
上传完整日志和错误报告压缩包

**Comment by MINECRAFTGUIYU** [comment]
> 上传完整日志和错误报告压缩包
[错误报告-2023-7-8_9.08.09.zip](https://github.com/Hex-Dragon/PCL2/files/11987105/-2023-7-8_9.08.09.zip)

完整日志指的是Log1~5一整个吗？

**Comment by ZHAOSBC** [comment]
遇到了相同的问题，在1.12.2的一些比较新的forge版本上，会自动选择JRE17导致游戏崩溃

**Comment by ZHAOSBC** [comment]
log1~5和错误报告如下：
[logs.zip](https://github.com/Hex-Dragon/PCL2/files/11995473/logs.zip)
[错误报告-2023-7-9_23.04.33.zip](https://github.com/Hex-Dragon/PCL2/files/11995474/-2023-7-9_23.04.33.zip)

**Comment by ZHAOSBC** [comment]
日志里显示java版本需求最高为999.999.999.999

**Comment by hellominecraftlauncher** [comment]
这个我从日志找到过，从PCL导出的错误包内，写着已找到Java：8、11、17等，但启动游戏显示的是已使用Java17启动游戏，在HMCL的kook群有案例，原先我以为是概率触发，直到我朋友也这样。（我想交issue，但是因为以前的事被屏蔽）

**Comment by MINECRAFTGUIYU** [comment]
5D95-3A5F-8375-5FF9

**Comment by LTCatt** [comment]
你的解锁码：2KQatrhrUnvj1d+EO3uIBCJIkrCgagwP
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by MINECRAFTGUIYU** [comment]
1DCE-1BF9-71E1-875C

**Comment by LTCatt** [comment]
你的解锁码：o6Nni3cfgUUnw43jKDXiF8b+2RjdKQuD
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
