### ISSUE TITLE
游戏显示minecraft出现错误

### ISSUE THREAD

**Issue by SHINIHAONIHAOSHI** [Hex-Dragon/PCL2#2201]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

jlw: native file exists: 'C:\Users\a1110\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
jlw: existing native file 'C:\Users\a1110\AppData\Roaming\PCL\libjlw-1.3.2.dll' failed to load, trying to overwrite.
jlw: releasing native file to 'C:\Users\a1110\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\a1110\AppData\Roaming\PCL\libjlw-1.3.2.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at oolloo.jlw.ArgLoader.loadNative(ArgLoader.java:122)
	at oolloo.jlw.ArgLoader.<init>(ArgLoader.java:19)
	at oolloo.jlw.Wrapper.main(Wrapper.java:24)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11994200/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11994201/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11994202/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11994203/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11994204/Log5.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/11994208/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/11994209/Log5.txt)

### 错误报告、日志与附件

jlw: native file exists: 'C:\Users\a1110\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
jlw: existing native file 'C:\Users\a1110\AppData\Roaming\PCL\libjlw-1.3.2.dll' failed to load, trying to overwrite.
jlw: releasing native file to 'C:\Users\a1110\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\a1110\AppData\Roaming\PCL\libjlw-1.3.2.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at oolloo.jlw.ArgLoader.loadNative(ArgLoader.java:122)
	at oolloo.jlw.ArgLoader.<init>(ArgLoader.java:19)
	at oolloo.jlw.Wrapper.main(Wrapper.java:24)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/11994205/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/11994206/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/11994207/Log3.txt)

**Comment by MM-Rabbit** [comment]
这...可能不是PCL2的问题吧...要不你尝试使用D:\java\bin\目录下的Open JDK 17试试？

**Comment by hejiehao** [comment]
换一个java

**Comment by youzi-2333** [comment]
与 #1108 重复。
下次提交前，可以先使用 GitHub 搜索功能（Issues 页面，上面有个放大镜的文本框，直接输入内容即可搜索）进行搜索，感谢配合。
