### ISSUE TITLE
下载、安装整合包或带有Forge原版游戏时安装 Mod 加载器（方式 A）失败

### ISSUE THREAD

**Issue by 1220475180** [Hex-Dragon/PCL2#2539]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题是 PCL2 导致的，和我的网络环境无关。
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

用HMCL启动器不存在这个问题。
只有安装 Mod 加载器（方式 A）会有这个问题，其他安装 Mod 加载器（方式 B）没有问题。

### 重现步骤

1、启动器上方点击下载
2、自动安装-1.20、1.19、1.18等-选择任意Forge-开始安装
3、下载 Forge 47.1.44失败
→ 安装 Mod 加载器（方式 A）失败
→ 安装新 Forge 版本失败
→ Forge 安装器出错，日志结束部分为：
	... 6 more
Caused by: java.lang.NullPointerException
	at net.minecraftforge.installer.json.Util.readFully(Util.java:94)
	at net.minecraftforge.installer.json.Util.loadInstallProfile(Util.java:43)
	... 11 more
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__12-0._Lambda$__0()
   在 PCL.ModDownloadLib.ForgeInjector(String Target, LoaderTask`2 Task, String McFolder)
   在 PCL.ModDownloadLib._Closure$__37-0._Lambda$__7(LoaderTask`2 Task)

### 日志与附件

[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12387424/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12387425/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12387426/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12387427/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12387428/Log2.txt)

**Comment by LTCatt** [comment]
无法复现，其他人可以复现吗？
你自己重复安装还会固定出现这个问题吗？

1.20.1-Forge_47.1.44

jlw: native file exists: 'C:\ProgramData\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.bangbang93.ForgeInstaller.main(ForgeInstaller.java:31)
	... 6 more
Caused by: java.lang.NullPointerException
	at net.minecraftforge.installer.json.Util.readFully(Util.java:94)
	at net.minecraftforge.installer.json.Util.loadInstallProfile(Util.java:43)
	... 11 more

**Comment by SALTWOOD** [comment]
无法复现，尝试切换Java

**Comment by LTCatt** [comment]
怀疑是 Java 或者文件故障，如果你在更换 Java 后依然重复出现该 Bug，或者其他人可以重现该 Bug，再考虑修复

**Comment by 1220475180** [comment]
尝试过更换，重新下载java都不好用
我尝试了下载所有版本，发现1.13以前的安装 Mod 加载器为（方式 B）1.13以后为（方式 A）附上了视频文件。







浅花迷人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hex-Dragon/PCL2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月21日(星期一) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hex-Dragon/PCL2] 下载、安装整合包或带有Forge原版游戏时安装 Mod 加载器（方式 A）失败 (Issue #2539)





 
无法复现，尝试切换Java
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

2023-08-21 17-25-20.mkv (94.78M, 2023年09月20日 17:26 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=783163361ae471ca18c8dd7e1261501f4c4500060505045319060200034c000905534e015704041d56025b535503505655505b54347662020403501b04594f02051152011953571d06014d5b5f17620d&code=41c64ab0

**Comment by LTCatt** [comment]
Caused by: java.lang.NullPointerException
at net.minecraftforge.installer.json.Util.readFully(Util.java:94)
at net.minecraftforge.installer.json.Util.loadInstallProfile(Util.java:43)

这个看上去更像是 Forge 安装包文件有问题或者损坏，但其他人包括我都没法复现，我不觉得这是启动器导致的……

**Comment by Qiong-Mengzi** [comment]
我的一个朋友也出现了这个问题

![3](https://github.com/Hex-Dragon/PCL2/assets/165121660/08bd6d8e-29f5-4678-bc7b-740cb7be4422)

于2024/04/24 21:06:28

但是我同样无法复现该bug

![Simeji_2024-4-24_21-52-10](https://github.com/Hex-Dragon/PCL2/assets/165121660/b9a55dcd-b748-4831-ad14-d1c1fc30f433)

![Simeji_2024-4-24_21-52-18](https://github.com/Hex-Dragon/PCL2/assets/165121660/21cc2754-a253-4ed2-9d9b-411ca35d964b)

使用OpenJDK17尝试复现。朋友的Java版本未知（由于我们平常玩的版本为1.16.5~1.20.1，故不存在java不兼容的情况）

由于朋友目前没有提供日志文件，故无法添加该附件。

**Comment by JingHai-Lingyun** [comment]
如果需要分析问题的原因的话请上传日志

**Comment by LTCatt** [comment]
@Qiong-Mengzi 图中的报错更可能是因为没有更新 PCL，如果更新后依然出错可以另开 issue

**Comment by wuliaodexiaoluo** [comment]
或许和 OptiFine 一样是随机到了不支持断点续传的下载源？

**Comment by allMagicNB** [comment]
> 唔，看起来这是一个相当难以复现的bug...
> 
> 刚刚我的朋友已经成功了

你的朋友使用的是最新版 PCL2 吗？

**Comment by LTCatt** [comment]
@fengguowudi 这不是同一个 issue，新开一个

**Comment by Rolandkkkk** [comment]
我也有这个问题，然后怀疑是中文路径的的问题。
在改了路径后这个问题解决了
所以是路径的问题吗？

**Comment by LTCatt** [comment]
请上传对应的日志，开一个新 issue
