### ISSUE TITLE
PCL 提示 “Minecraft 出现错误”

### ISSUE THREAD

**Issue by KyonoMasaki** [Hex-Dragon/PCL2#2758]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

偶尔启动出现问题，有时很频繁

### PCL 错误报告、日志与附件

[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/12840176/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/12840177/Log5.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/12840178/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/12840179/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/12840180/Log3.txt)

**Comment by JingHai-Lingyun** [comment]
崩溃见于 Log5 
第 1460 行往下（游戏日志）
```
Caused by: java.lang.ClassCastException: class net.minecraft.class_2827 cannot be cast to class meteordevelopment.meteorclient.mixin.PlayerMoveC2SPacketAccessor (net.minecraft.class_2827 and meteordevelopment.meteorclient.mixin.PlayerMoveC2SPacketAccessor are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @42dafa95)
	at meteordevelopment.meteorclient.systems.modules.movement.NoFall.onSendPacket(NoFall.java:126) ~[Meteor-Client-Mod-Fabric-1.20.1.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[Meteor-Client-Mod-Fabric-1.20.1.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:61) ~[Meteor-Client-Mod-Fabric-1.20.1.jar:?]
	at net.minecraft.class_2535.handler$dnd000$meteor-client$onSendPacketHead(class_2535.java:4573) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10743(class_2535.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_2883(class_634.java:9247) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_3136(class_746.java:276) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:230) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	... 14 more
```
第 1877 行往下（启动器日志）
```
[06:31:37.249] [Control] 普通弹窗：Minecraft 出现错误
你的游戏遇到了一些问题，这可能是某些 Mod 所引起的，PCL 找到了以下可疑的关键词：
 - meteordevelopment, meteorclient, systems, modules, orbit, listeners

如果你知道这些关键词对应的 Mod，那么有可能就是它引起的错误，你也可以查看错误报告获取详情。
如果要寻求帮助，请向他人发送错误报告文件，而不是发送这个窗口的截图。
[06:31:49.788] [Control] 按下按钮：确定
```
看起来是 Meteor Mod 在处理 NoFall 发包事件中出现异常
此问题由模组引起，**不是** PCL2 能解决的问题。你可在 [提问板块](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E6%8F%90%E9%97%AE) 或其他 Minecraft 社区等地方提问

**Comment by KyonoMasaki** [comment]
Issue
