### ISSUE TITLE
操作背景图片时报错

### ISSUE THREAD

**Issue by jjy150418** [Hex-Dragon/PCL2#2946]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

报错，无法正常操作

### 重现步骤

1、点击个性化
2、点击背景图片一栏中的任意一个按钮

### 日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/13539042/Log1.txt)
[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/13539038/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/13539039/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/13539040/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/13539041/Log5.txt)

**Comment by burningtnt** [comment]
```
[21:15:58.321] 刷新背景图片时出现未知错误：Could not find a part of the path 'E:\迅雷下载\Snapshot 2.6.4\PCL\Pictures'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Microsoft.VisualBasic.FileIO.FileSystem.FindPaths(FileOrDirectory FileOrDirectory, String directory, String wildCard)
   at Microsoft.VisualBasic.FileIO.FileSystem.FindFilesOrDirectories(FileOrDirectory FileOrDirectory, String directory, SearchOption searchType, String[] wildcards, Collection`1 Results)
   at Microsoft.VisualBasic.FileIO.FileSystem.FindFilesOrDirectories(FileOrDirectory FileOrDirectory, String directory, SearchOption searchType, String[] wildcards)
   at PCL.ModMain.BackgroundRefresh(Boolean IsHint, Boolean Refresh)
错误类型：System.IO.DirectoryNotFoundException
```

你检查一下 `E:\迅雷下载\Snapshot 2.6.4\PCL\Pictures` 这个路径，看看到哪一级没有了
