### ISSUE TITLE
使用特定 ID 无法离线启动游戏：Invalid UUID string

### ISSUE THREAD

**Issue by sQianchangyub** [Hex-Dragon/PCL2#3343]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

1.20.4窗口未出现时直接报错

### PCL 错误报告、日志与附件

[错误报告-2024-2-17_14.17.46.zip](https://github.com/Hex-Dragon/PCL2/files/14317943/-2024-2-17_14.17.46.zip)

### HMCL 启动脚本

[1.zip](https://github.com/Hex-Dragon/PCL2/files/14317950/1.zip)

**Comment by allMagicNB** [comment]
删除重新安装≠未安装任何Mod

**Comment by JingHai-Lingyun** [comment]
日志提示
```
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 00000XXXXXXXXXXXXXXXXXXXXX5E09C
```
传入了一个意外的 UUID

**Comment by sQianchangyub** [comment]
> 删除重新安装≠未安装任何Mod

删除重新安装的是游戏本体,没装模组

**Comment by sQianchangyub** [comment]
> 日志提示
> 
> ```
> Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 00000XXXXXXXXXXXXXXXXXXXXX5E09C
> ```
> 
> 传入了一个意外的 UUID 请直接用 PCL 启动器启动，而不是崩溃日志里的 （这个脚本中的 UUID 会被打码）`启动脚本.bat`

就是直接启动的,那个脚本是hmcl生成的

**Comment by allMagicNB** [comment]
你这使用了两个不同的Java21……

**Comment by wuliaodexiaoluo** [comment]
一个MSJDK，一个不知名JDK。。。。。。
我下个Adoptium逝世

**Comment by allMagicNB** [comment]
请使用不同启动器但同一Java进行启动

**Comment by pengjunshuai** [comment]
目前我有朋友也遇到了相同的错误
[错误报告-2024-2-17_23.49.31.zip](https://github.com/Hex-Dragon/PCL2/files/14319403/-2024-2-17_23.49.31.zip)
其错误报告基本相同
感觉不是Java的问题的说

**Comment by allMagicNB** [comment]
```
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 00000XXXXXXXXXXXXXXXXXXXXXXXXX
```
这看起来都是离线用户的UUID问题……

**Comment by sQianchangyub** [comment]
> 请使用不同启动器但同一Java进行启动再上传PCL的错误报告/HMCL的启动脚本

具体怎么做？我还有一个启动器。Java一个是官网下的，一个是hmcl自己下的

**Comment by allMagicNB** [comment]
> > 请使用不同启动器但同一Java进行启动再上传PCL的错误报告/HMCL的启动脚本
> 
> 具体怎么做？我还有一个启动器。Java一个是官网下的，一个是hmcl自己下的

改一下PCL2的`游戏 Java`选项为`C:\Program Files\Microsoft\jdk-21.0.2.13-hotspot\bin\java.exe`

**Comment by wuliaodexiaoluo** [comment]
``` log
[14:14:48.755] [Launch] -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Dfml.ignoreInvalidMinecraftCertificates=True -Dfml.ignorePatchDiscrepancies=True -Dlog4j2.formatMsgNoLookups=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path="D:\Minecraft\.minecraft\versions\1.20.4\1.20.4-natives" -Djna.tmpdir="D:\Minecraft\.minecraft\versions\1.20.4\1.20.4-natives" -Dorg.lwjgl.system.SharedLibraryExtractPath="D:\Minecraft\.minecraft\versions\1.20.4\1.20.4-natives" -Dio.netty.native.workdir="D:\Minecraft\.minecraft\versions\1.20.4\1.20.4-natives" -Dminecraft.launcher.brand=PCL -Dminecraft.launcher.version=313 -cp "D:\Minecraft\.minecraft\libraries\com\github\oshi\oshi-core\6.4.5\oshi-core-6.4.5.jar;D:\Minecraft\.minecraft\libraries\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar;D:\Minecraft\.minecraft\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;D:\Minecraft\.minecraft\libraries\com\google\guava\guava\32.1.2-jre\guava-32.1.2-jre.jar;D:\Minecraft\.minecraft\libraries\com\ibm\icu\icu4j\73.2\icu4j-73.2.jar;D:\Minecraft\.minecraft\libraries\com\mojang\authlib\6.0.52\authlib-6.0.52.jar;D:\Minecraft\.minecraft\libraries\com\mojang\blocklist\1.0.10\blocklist-1.0.10.jar;D:\Minecraft\.minecraft\libraries\com\mojang\brigadier\1.2.9\brigadier-1.2.9.jar;D:\Minecraft\.minecraft\libraries\com\mojang\datafixerupper\6.0.8\datafixerupper-6.0.8.jar;D:\Minecraft\.minecraft\libraries\com\mojang\logging\1.1.1\logging-1.1.1.jar;D:\Minecraft\.minecraft\libraries\com\mojang\patchy\2.2.10\patchy-2.2.10.jar;D:\Minecraft\.minecraft\libraries\com\mojang\text2speech\1.17.9\text2speech-1.17.9.jar;D:\Minecraft\.minecraft\libraries\commons-codec\commons-codec\1.16.0\commons-codec-1.16.0.jar;D:\Minecraft\.minecraft\libraries\commons-io\commons-io\2.13.0\commons-io-2.13.0.jar;D:\Minecraft\.minecraft\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\Minecraft\.minecraft\libraries\io\netty\netty-buffer\4.1.97.Final\netty-buffer-4.1.97.Final.jar;D:\Minecraft\.minecraft\libraries\io\netty\netty-codec\4.1.97.Final\netty-codec-4.1.97.Final.jar;D:\Minecraft\.minecraft\libraries\io\netty\netty-common\4.1.97.Final\netty-common-4.1.97.Final.jar;D:\Minecraft\.minecraft\libraries\io\netty\netty-handler\4.1.97.Final\netty-handler-4.1.97.Final.jar;D:\Minecraft\.minecraft\libraries\io\netty\netty-resolver\4.1.97.Final\netty-resolver-4.1.97.Final.jar;D:\Minecraft\.minecraft\libraries\io\netty\netty-transport-classes-epoll\4.1.97.Final\netty-transport-classes-epoll-4.1.97.Final.jar;D:\Minecraft\.minecraft\libraries\io\netty\netty-transport-native-unix-common\4.1.97.Final\netty-transport-native-unix-common-4.1.97.Final.jar;D:\Minecraft\.minecraft\libraries\io\netty\netty-transport\4.1.97.Final\netty-transport-4.1.97.Final.jar;D:\Minecraft\.minecraft\libraries\it\unimi\dsi\fastutil\8.5.12\fastutil-8.5.12.jar;D:\Minecraft\.minecraft\libraries\net\java\dev\jna\jna-platform\5.13.0\jna-platform-5.13.0.jar;D:\Minecraft\.minecraft\libraries\net\java\dev\jna\jna\5.13.0\jna-5.13.0.jar;D:\Minecraft\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;D:\Minecraft\.minecraft\libraries\org\apache\commons\commons-compress\1.22\commons-compress-1.22.jar;D:\Minecraft\.minecraft\libraries\org\apache\commons\commons-lang3\3.13.0\commons-lang3-3.13.0.jar;D:\Minecraft\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;D:\Minecraft\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.4.16\httpcore-4.4.16.jar;D:\Minecraft\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.19.0\log4j-api-2.19.0.jar;D:\Minecraft\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.19.0\log4j-core-2.19.0.jar;D:\Minecraft\.minecraft\libraries\org\apache\logging\log4j\log4j-slf4j2-impl\2.19.0\log4j-slf4j2-impl-2.19.0.jar;D:\Minecraft\.minecraft\libraries\org\joml\joml\1.10.5\joml-1.10.5.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.2\lwjgl-glfw-3.3.2.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.2\lwjgl-glfw-3.3.2-natives-windows.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.2\lwjgl-glfw-3.3.2-natives-windows-arm64.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.3.2\lwjgl-glfw-3.3.2-natives-windows-x86.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.2\lwjgl-jemalloc-3.3.2.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.2\lwjgl-jemalloc-3.3.2-natives-windows.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.2\lwjgl-jemalloc-3.3.2-natives-windows-arm64.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.3.2\lwjgl-jemalloc-3.3.2-natives-windows-x86.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.2\lwjgl-openal-3.3.2.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.2\lwjgl-openal-3.3.2-natives-windows.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.2\lwjgl-openal-3.3.2-natives-windows-arm64.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.3.2\lwjgl-openal-3.3.2-natives-windows-x86.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.2\lwjgl-opengl-3.3.2.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.2\lwjgl-opengl-3.3.2-natives-windows.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.2\lwjgl-opengl-3.3.2-natives-windows-arm64.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.3.2\lwjgl-opengl-3.3.2-natives-windows-x86.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.2\lwjgl-stb-3.3.2.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.2\lwjgl-stb-3.3.2-natives-windows.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.2\lwjgl-stb-3.3.2-natives-windows-arm64.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.3.2\lwjgl-stb-3.3.2-natives-windows-x86.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.3.2\lwjgl-tinyfd-3.3.2.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.3.2\lwjgl-tinyfd-3.3.2-natives-windows.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.3.2\lwjgl-tinyfd-3.3.2-natives-windows-arm64.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.3.2\lwjgl-tinyfd-3.3.2-natives-windows-x86.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl\3.3.2\lwjgl-3.3.2.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl\3.3.2\lwjgl-3.3.2-natives-windows.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl\3.3.2\lwjgl-3.3.2-natives-windows-arm64.jar;D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl\3.3.2\lwjgl-3.3.2-natives-windows-x86.jar;D:\Minecraft\.minecraft\libraries\org\slf4j\slf4j-api\2.0.7\slf4j-api-2.0.7.jar;D:\Minecraft\.minecraft\versions\1.20.4\1.20.4.jar" -Xmn256m -Xmx5222m -Dlog4j2.formatMsgNoLookups=true --add-exports cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher=ALL-UNNAMED -Doolloo.jlw.tmpdir="C:\ProgramData\PCL" -jar "C:\ProgramData\PCL\JavaWrapper.jar" net.minecraft.client.main.Main --username 111 --version 1.20.4 --gameDir "D:\Minecraft\.minecraft" --assetsDir "D:\Minecraft\.minecraft\assets" --assetIndex 12 --uuid 00000XXXXXXXXXXXXXXXXXXXXX5E09C --accessToken 00000XXXXXXXXXXXXXXXXXXXXX5E09C --clientId ${clientid} --xuid ${auth_xuid} --userType msa --versionType PCL --width 854 --height 480 
```

我有一个猜测，会不会是PCL出了Bug误将隐藏的uuid当作真实uuid传入了Java，因为启动脚本不会有这个问题
可能是计算机病毒导致的？

**Comment by youzi-2333** [comment]
请尽快补充信息，一定时间内未补充将会被关闭，感谢您的理解

**Comment by pengjunshuai** [comment]
![5a53c68024afeb65a5f35147d0b1fd89](https://github.com/Hex-Dragon/PCL2/assets/108521813/f9bfee7a-dcc8-4265-9f71-04deabb3d
![Uploading 5a53c68024afeb65a5f35147d0b1fd89.jpg…]()
d14)

**Comment by pengjunshuai** [comment]
![5a53c68024afeb65a5f35147d0b1fd89](https://github.com/Hex-Dragon/PCL2/assets/108521813/7d11e4cb-8814-4437-85d6-bee7cb8f7d80)
![5a53c68024afeb65a5f35147d0b1fd89](https://github.com/Hex-Dragon/PCL2/assets/108521813/56176cb7-eb8d-45fe-8520-5e37cca4cc14)

**Comment by pengjunshuai** [comment]
在切换随机皮肤后成功启动，看来是由于这部分代码导致的问题

**Comment by sQianchangyub** [comment]
我明天试试

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月28日 23:13 |
| 收件人 | Hex-Dragon/PCL2 ***@***.***> |
| 抄送人 | sQianchangyub ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] 1.20.4无法运行(删除模组后) (Issue #3343) |

在切换随机皮肤后成功启动，看来是由于这部分代码导致的问题

**Comment by sQianchangyub** [comment]
这怎么发图片

**Comment by hejiehao** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/98140773/ee3f1859-ae8f-4b03-92fc-361e3ef001b1)
点这里或者把图片粘贴上去

**Comment by wuliaodexiaoluo** [comment]
> 这怎么发图片

被添加了处理中的 Label 请不要自己 Close As Completed

**Comment by allMagicNB** [comment]
> > 这怎么发图片
> 
> 被添加了处理中的 Label 请不要自己 Close As Completed

人家 Reopen 了不小心点到了你就别再指责了……

**Comment by wuliaodexiaoluo** [comment]
> 人家 Reopen 了不小心点到了你就别再指责了……

你貌似误解了我的话的语气。。。。
首先我没有指责他，我只是在提示，如果是指责，这段话不应该出现 ```请``` 这个字
这个才是表示指责
被添加了处理中的 Label 不要自己 Close As Completed
请认真解读他人评论所带有的情感，而不是依照自己的理解做出相当随意的评价（至少我认为相当随意）

**Comment by mc-124** [comment]
这个uuid怎么是31位的？是PCL2把中间换成X的时候搞的还是生成uuid的时候发生了错误？

**Comment by mc-124** [comment]
我在测试后发现：一些较新的版本（测试版本1.20.4）的uuid中存在X（不是16进制数字的字符）或删去`-`后长度!=32位会导致这个错误，老版本（测试版本1.12.2）中不存在此问题：
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
        at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 3f30bef96035408e948a5d3bd477925
        at java.base/java.util.UUID.fromString1(UUID.java:282)
        at java.base/java.util.UUID.fromString(UUID.java:260)
        at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
        at net.minecraft.client.main.Main.main(SourceFile:151)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
```
这与author上传的崩溃输出基本一样
```
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
jlw: native file exists: 'C:\ProgramData\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 00000XXXXXXXXXXXXXXXXXXXXX5E09C
	at java.base/java.util.UUID.fromString1(UUID.java:282)
	at java.base/java.util.UUID.fromString(UUID.java:260)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:151)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 3 more
```
并且author发来的启动脚本与PCL2日志中，发现：
```py
len("00000XXXXXXXXXXXXXXXXXXXXX5E09C") # 这是提取到的uuid
31
```
uuid长度不为32，导致发生错误。
那导致PCL2生成31位uuid的原因是什么？？

**Comment by mc-124** [comment]
什么逆天bug。。。 让龙猫做个名字是EW+皮肤是Steve时拒绝启动或警告吧？顺便去mojang交个bug

**Comment by mc-124** [comment]
> 怪事来了 ![image](https://private-user-images.githubusercontent.com/160083863/319601492-d95998aa-a4fc-4194-9b63-d025aca7c8c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzgzMDAsIm5iZiI6MTcxMjIzODAwMCwicGF0aCI6Ii8xNjAwODM4NjMvMzE5NjAxNDkyLWQ5NTk5OGFhLWE0ZmMtNDE5NC05YjYzLWQwMjVhY2E3YzhjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMzQwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTQ0ODU0YTgwMGJjODc0YWI0MTQ3ZjhhZjllYzhhZThlMjYwMWEyMjRkZjk5Nzk3MWQzOWJmYzQwZmFlMTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mAgBf9x7CgAXo4XYn53L3k-ZKYDu8wzoisZAUIfQBcc) 如果使用 Issue 作为用户名指定 Steve 皮肤启动一点问题都没有 但是使用 EW 作为用户名指定 Steve 皮肤启动就是 Invalid UUID ![image](https://private-user-images.githubusercontent.com/160083863/319602116-36ca6eac-acf4-4e89-94a1-c6f04acf0d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzgzMDAsIm5iZiI6MTcxMjIzODAwMCwicGF0aCI6Ii8xNjAwODM4NjMvMzE5NjAyMTE2LTM2Y2E2ZWFjLWFjZjQtNGU4OS05NGExLWM2ZjA0YWNmMGQzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMzQwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTBjOTZkMjU3YzFmMDg2OTBlMTkyMTNlOWIwNTMwNzIxMzg2YjNhMmQ3ZDVkN2M2YjJiYzFiZjNiYTMxZDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LWt7TpeR6WI_Xj-mDX61VFBz1kLw9Z9LJ6UnjpSsy00)

我发现报错的原因是名字是EW时PCL2传入的uuid会丢失两个字符，不知道为什么

**Comment by wuliaodexiaoluo** [comment]
> > 怪事来了 ![image](https://private-user-images.githubusercontent.com/160083863/319601492-d95998aa-a4fc-4194-9b63-d025aca7c8c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzgzMDAsIm5iZiI6MTcxMjIzODAwMCwicGF0aCI6Ii8xNjAwODM4NjMvMzE5NjAxNDkyLWQ5NTk5OGFhLWE0ZmMtNDE5NC05YjYzLWQwMjVhY2E3YzhjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMzQwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTQ0ODU0YTgwMGJjODc0YWI0MTQ3ZjhhZjllYzhhZThlMjYwMWEyMjRkZjk5Nzk3MWQzOWJmYzQwZmFlMTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mAgBf9x7CgAXo4XYn53L3k-ZKYDu8wzoisZAUIfQBcc) 如果使用 Issue 作为用户名指定 Steve 皮肤启动一点问题都没有 但是使用 EW 作为用户名指定 Steve 皮肤启动就是 Invalid UUID ![image](https://private-user-images.githubusercontent.com/160083863/319602116-36ca6eac-acf4-4e89-94a1-c6f04acf0d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzgzMDAsIm5iZiI6MTcxMjIzODAwMCwicGF0aCI6Ii8xNjAwODM4NjMvMzE5NjAyMTE2LTM2Y2E2ZWFjLWFjZjQtNGU4OS05NGExLWM2ZjA0YWNmMGQzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMzQwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTBjOTZkMjU3YzFmMDg2OTBlMTkyMTNlOWIwNTMwNzIxMzg2YjNhMmQ3ZDVkN2M2YjJiYzFiZjNiYTMxZDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LWt7TpeR6WI_Xj-mDX61VFBz1kLw9Z9LJ6UnjpSsy00)
> 
> 我发现报错的原因是名字是EW时PCL2传入的uuid会丢失两个字符，不知道为什么

#3361 请
