### ISSUE TITLE
无法启动1.5.2原版以及以下版本。初步判断是版本隔离问题。

### ISSUE THREAD

**Issue by rechalow** [Hex-Dragon/PCL2#336]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我无法启动有关于1.5.2原版及以下版本的游戏！
初步判断无法启动的原因是没开版本隔离。因为我一般不喜欢开版本隔离的！
然后，对于版本隔离来说，1.5.2及以下版本，如果没开版本隔离，一旦启动就会立刻报错。其次，如果开了Forge，甚至无法启动直接抛出报错的那种。

详细错误截图附在下面了。请过目！！

### 错误报告、日志与附件

以下是错误日志
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/9946516/Log1.txt)
[LatestLaunch.txt](https://github.com/Hex-Dragon/PCL2/files/9946507/LatestLaunch.txt)
以下是原版启动【此时未开版本隔离】
![bugpic](https://user-images.githubusercontent.com/61784773/200187717-cf5f264c-5746-46c3-ba06-f9b7db761e40.png)
以下是直接启动Forge版本【此时开了版本隔离】
![bugpic2](https://user-images.githubusercontent.com/61784773/200187771-0e4bb0fb-059d-4bdf-b30e-53f2759c5961.png)
报错信息直接发给你看就好了，不想传文件了。。。
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option ['assetsDir'], but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:178)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:40)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
	... 6 more
我有个建议，如果能修好启动Forge的话，也是能启动原版的吧。。

**Comment by Super-XiaoNian** [comment]
老版本了，其游戏加载可能和新版本不一样，所以我建议开版本隔离。
至于forge，你用java7启动试试。

**Comment by King-ming136121** [comment]
![image](https://user-images.githubusercontent.com/110441378/200275196-a2a3e5e8-e07d-47a5-9744-1a86ab0a12fa.png)
使用1.5.2原版并未复现出此问题！1.5.2的Forge版则会复现出此问题...

**Comment by Super-XiaoNian** [comment]
留企鹅，我看看。

**Comment by Super-XiaoNian** [comment]
c，PCL2还真启动不着，显示 joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option ['assetsDir'], but you asked for only one
我亲自去Forge下载了个安装器，然后启动，报错提示deobfuscation_data_1.5.2在服务器上已经被删，所以下载失败就没成功启动。

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/200290161-385c0dad-1945-499f-9120-7d70ecbed1c8.png)

我没法重现，谁来个使用快照版 2.4.0 的错误报告？

**Comment by FUTURE16524** [comment]
我的原版没有错误（版本隔离关闭）
但是加上forge也是这样
[错误报告-2022-11-7_19.49.27.zip](https://github.com/Hex-Dragon/PCL2/files/9951115/-2022-11-7_19.49.27.zip)

**Comment by Super-XiaoNian** [comment]
> ![image](https://user-images.githubusercontent.com/40348278/200290161-385c0dad-1945-499f-9120-7d70ecbed1c8.png)
> 
> 我没法重现，谁来个使用快照版 2.4.1 的错误报告？ 完整的错误报告压缩包！

不是原版。是带Forge的1.5.2。

**Comment by King-ming136121** [comment]
> ![图像](https://user-images.githubusercontent.com/40348278/200290161-385c0dad-1945-499f-9120-7d70ecbed1c8.png)
> 
> 我没法重现，谁来个使用快照版 2.4.1 的错误报告？ 完整的错误报告压缩包！

不是原版！而是关闭版本隔离的forge版

**Comment by Super-XiaoNian** [comment]
破案了。
龙猫你看看这两个文件的不同点(我不知道你是在哪获取的Forge版本)。
[Desktop.zip](https://github.com/Hex-Dragon/PCL2/files/9951257/Desktop.zip)
里面有两份json，你比对一下
一份来自Forge官网安装包上提取的json
一份是来自PCL2自动安装的Forge。

**Comment by FUTURE16524** [comment]
> 

打开版本隔离也是这样

**Comment by FUTURE16524** [comment]
> > ![图像](https://user-images.githubusercontent.com/40348278/200290161-385c0dad-1945-499f-9120-7d70ecbed1c8.png)
> > 我没法重现，谁来个使用快照版 2.4.1 的错误报告？ 完整的错误报告压缩包！
> 
> 不是原版！而是关闭版本隔离的forge版

打开版本隔离也是这样

**Comment by LTCatt** [comment]
修复了一个导致 1.5.2 Forge 安装后的 json 出现问题的 bug，但是使用正确的 json 依然启动失败。
换 HMCL 安装并启动 1.5.2 Forge 也失败，估计不是 PCL2 的问题而是 Forge 的问题。

1.5.2 原版启动失败不是这个 Bug 导致的，我也没法复现，建议重新交一个 issue，然后上传错误报告压缩包。

**Comment by LTCatt** [comment]
确认了目前 1.5.2 Forge 应该是 Forge 官方的下载源也出了问题，是 Forge 那边的 Bug 导致无法启动。

**Comment by Super-XiaoNian** [comment]
> 确认了目前 1.5.2 Forge 应该是 Forge 官方的下载源也出了问题，是 Forge 那边的 Bug 导致无法启动。

但我用Forge官方提供的安装器，安装完后，虽然报了错，但报错显示，远程服务器没有该依赖库文件，。不也证明，jar和json是没问题的。
PCL2 Forge下载源是哪来的？能提供API吗？

**Comment by LTCatt** [comment]
json 问题已经修了……

**Comment by LTCatt** [comment]
你的解锁码：CXHhLZl8Cvzb4nifMRo9O/ce9c7wmGvB
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
