### ISSUE TITLE
改进【第三方登录 : authlib-injector 或 littleskin】 登录逻辑

### ISSUE THREAD

**Issue by PAKingdom** [Hex-Dragon/PCL2#3441]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

功能需求：选定了第三方登录的整合包每次启动希望自动刷新密钥。

当我尝试使用启动器的更换角色功能和退出重新登录后，此问题问题解决

PCL2不像其他启动器无缓存(指在新的文件夹启动时需要重新输入验证信息)。每一次登录都会缓存。
如果缓存 过期/与服务器不匹配 会导致使用authlib-injector验证无法连接至服务器

authlib-injector.log ↓↓↓
```authlib-injector.log
Logging started at 2024-02-28T07:25:26.657Z
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: https://XXXXXX/api/yggdrasil
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Enable MC-52974 Workaround
[authlib-injector] [INFO] Enable MC-52974 Workaround for 1.7.10
[authlib-injector] [INFO] Httpd is running on port 18881
[authlib-injector] [INFO] Transformed [net.minecraft.client.entity.AbstractClientPlayer] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.util.Session] with [1.7.10 MC-52974 Workaround (Session)]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [MC-52974 Workaround]
[authlib-injector] [INFO] Transformed [com.emoniph.witchery.entity.EntityReflection] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.network.play.server.S0CPacketSpawnPlayer] with [1.7.10 MC-52974 Workaround (S0CPacketSpawnPlayer)]
[authlib-injector] [INFO] Transformed [com.emoniph.witchery.common.ExtendedPlayer] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication] with [Constant URL Transformer]
[authlib-injector] [WARNING] Reverse proxy error
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1249)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1247)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1246)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at moe.yushi.authlibinjector.httpd.URLProcessor.reverseProxy(URLProcessor.java:192)
	at moe.yushi.authlibinjector.httpd.URLProcessor.access$400(URLProcessor.java:47)
	at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:158)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler$$Lambda$2787/323059136.apply(Unknown Source)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
	... 24 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 30 more
``` 

### 原因

当使用 authlib-injector 进行登录PCL2会进行缓存。缓存后会遇到一个问题，如果Yggdrasil服务器更新了SSL证书，启动游戏进入游戏后会传给 多人游戏(服务器) 一个ID=null的参数，这是因为Yggdrasil服务器的某些信息更新，启动器端PCL2未刷新登录信息，导致无法通过验证

**Comment by LTCatt** [comment]
是 #2313 ？
如果是 #2313 的话，可以去那里补充能用作测试的信息 Orz

**Comment by deep-dark-forest** [comment]
那这个可以close了吗

**Comment by JingHai-Lingyun** [comment]
@PAKingdom 请尽快补充信息，否则将因为超时而关闭

**Comment by deep-dark-forest** [comment]
他已经去#2313 那补充信息了，说明他同意龙猫说的[这句话](https://github.com/Hex-Dragon/PCL2/issues/3441#issuecomment-1968521866)，可以视为重复

**Comment by allMagicNB** [comment]
那么关了吧

**Comment by PAKingdom** [comment]
当启动器未刷新过期的TOKEN时，可以成功启动游戏但无法进入多人游戏服务器(因为没法过验证)。非常难以复现此问题。
常见于，一个月玩一次MC 然而认证服务器早已不认识你的TOKEN 因为已经过期了，
然后PCL2还拿过期的TOKEN启动游戏没有重新获取。由于PCL2的存储特性(保存密码)，
无论你在哪个文件夹打开，只要填入了这个第三方服务器，就会获取到这个”旧的TOKEN“ 
**能力有限我不知道他具体是哪个token没变**，这也许可能是[Yggdrasil](https://github.com/yushijinhun/authlib-injector/wiki/)的问题
~~(我承认这个回答有点自以为是~~ 

已[补充](https://github.com/Hex-Dragon/PCL2/issues/3441#issue-2158382213)日志

**Comment by LTCatt** [comment]
理论上是同一个 bug 引起的，不用 reopen
