### ISSUE TITLE
使用快照版 打开1.12.2原版我的世界 在打开就崩溃

### ISSUE THREAD

**Issue by 1esheng** [Hex-Dragon/PCL2#3496]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

打开1.12.2我的世界就立马崩溃

### PCL 错误报告、日志与附件

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-03-05 22:13
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:322)
	at ank.b(SourceFile:336)
	at ank.a(SourceFile:311)
	at ank.a(SourceFile:94)
	at ank.a(SourceFile:88)
	at anh.a(SourceFile:245)
	at anr.a(SourceFile:89)
	at aze.b(SourceFile:480)
	at axw.a(SourceFile:803)
	at axw.a(SourceFile:791)
	at on.c(SourceFile:115)
	at net.minecraft.server.MinecraftServer.l(SourceFile:328)
	at chd.a(SourceFile:114)
	at chd.j(SourceFile:130)
	at net.minecraft.server.MinecraftServer.run(SourceFile:434)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 99109328 bytes (94 MB) / 276824064 bytes (264 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8192m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Probably not. Jar signature remains and both client + server brands are untouched.

**Comment by burningtnt** [comment]
游戏本身问题，与 PCL2 无关

尝试删去游戏文件夹下的 options.txt 再试一次

**Comment by 1esheng** [comment]
你好删除后 同样没有用
新的log只有
[22:35:24] [Client thread/INFO]: Setting user: lesheng_

**Comment by zkitefly** [comment]
将崩溃报告上传

并尝试使用 hmcl 启动是否有出现问题

**Comment by 1esheng** [comment]
[错误报告-3-5-2024_11.19.59_PM.zip](https://github.com/Hex-Dragon/PCL2/files/14504568/-3-5-2024_11.19.59_PM.zip)

我尝试过hmcl了 启动到创建世界并且游玩没有问题

**Comment by allMagicNB** [comment]
没问题请上传日志

**Comment by 1esheng** [comment]
我该如何上传hmcl的日志

**Comment by allMagicNB** [comment]
在`通用->设置->启动器->通用->调试->导出启动器日志`中导出，导出后会自动保存到 HMCL 的所在路径中

**Comment by 1esheng** [comment]
![屏幕截图 2024-03-05 233145](https://github.com/Hex-Dragon/PCL2/assets/91392822/580b3295-32e9-4ddf-b90b-e214129dffed)
这是使用hmcl正常游玩的画面
我不知道该如何上传没问题的日志所以只能截屏了

**Comment by 1esheng** [comment]
[hmcl-exported-logs-2024-03-05T23-34-02.log](https://github.com/Hex-Dragon/PCL2/files/14504648/hmcl-exported-logs-2024-03-05T23-34-02.log)
我从新上传了hmcl的日志

**Comment by allMagicNB** [comment]
额，你要不然导出启动脚本吧……
在`游戏->你的版本->管理->生成启动脚本`中生成，随便选个地方保存后发上来

**Comment by 1esheng** [comment]
[启动脚本.zip](https://github.com/Hex-Dragon/PCL2/files/14504947/default.zip)

**Comment by 1esheng** [comment]
你好 我不确定我操作的对不对

**Comment by allMagicNB** [comment]
1.你启动的不是同一个游戏，你得调整下游戏路径，你这还是新安装的游戏
2.你启动时使用的 Java 不同，请指定具体 Java 为同一个后尝试复现，而不是使用`自动选择`选项

**Comment by allMagicNB** [comment]
加我 QQ 吧，我看看

**Comment by 1esheng** [comment]
以加

**Comment by SALTWOOD** [comment]
是一打开游戏就崩溃，还是打开存档才崩溃？重新安装会不会解决问题？真的没有安装别的模组吗？即使是optifine？

**Comment by 1esheng** [comment]
是的 当点击开启游戏时就崩溃。我尝试过重新安装不能解决问题。我没有安装任何的模组即使是optifine

**Comment by wuliaodexiaoluo** [comment]
> 是的 当点击开启游戏时就崩溃。我尝试过重新安装不能解决问题。我没有安装任何的模组即使是optifine

最好不要使用 Oracle JDK启动游戏的说
另外自备一个Java8，我看你用于启动的Java8版本实在太低的说(U51，还不如用wy的java的说)
另外你貌似是用高版本Java启动 Minecraft 的说（11/19），应该是成功启动的说，可以换这个版本（1.12.2原版应该支持11的说）

**Comment by wuliaodexiaoluo** [comment]
根据日志信息，应当是Java不完整，请前往 [清华大学开源软件镜像站 - Adoptium 镜像 Index of /Adoptium/8/jdk/x64/windows/](https://mirrors.tuna.tsinghua.edu.cn/Adoptium/8/jdk/x64/windows/) 下载 Java 解压到 PCL 文件夹

参考信息：游戏崩溃前的日志输出
```
[23:19:54] [Client thread/INFO]: Setting user: lesheng_
Exception in thread "Client thread" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.UnsatisfiedLinkError: no awt in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.awt.Toolkit$3.run(Toolkit.java:1636)
	at java.awt.Toolkit$3.run(Toolkit.java:1634)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
	at sun.awt.AppContext$2.run(AppContext.java:277)
	at sun.awt.AppContext$2.run(AppContext.java:266)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.AppContext.initMainAppContext(AppContext.java:266)
	at sun.awt.AppContext.access$400(AppContext.java:135)
	at sun.awt.AppContext$3.run(AppContext.java:321)
	at sun.awt.AppContext$3.run(AppContext.java:304)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.AppContext.getAppContext(AppContext.java:303)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:154)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at bib.<init>(SourceFile:390)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	... 6 more
```

**Comment by wuliaodexiaoluo** [comment]
又可以 Closed 了
为什么我还是没有 Collaborator
~是我不配吗？~

**Comment by MCSteve123** [comment]
> 又可以 Closed 了 为什么我还是没有 Collaborator ~是我不配吗？~

6
