### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Y1zZz** [Hex-Dragon/PCL2#3522]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 00000XXXXXXXXXXXXXXXXXXXX6D963
	at java.base/java.util.UUID.fromString1(UUID.java:280)
	at java.base/java.util.UUID.fromString(UUID.java:258)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:151)
	... 6 more

### PCL 错误报告、日志与附件

[PCL 启动器日志.txt](https://github.com/Hex-Dragon/PCL2/files/14612377/PCL.txt)
[游戏崩溃前的输出.txt](https://github.com/Hex-Dragon/PCL2/files/14612379/default.txt)

**Comment by wuliaodexiaoluo** [comment]
见 #3343 
``` Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 00000XXXXXXXXXXXXXXXXXXXX6D963 ```

**Comment by Y1zZz** [comment]
我搜索的时候不会找关键字……十分感谢！

**Comment by wuliaodexiaoluo** [comment]
点击一下 Closed as no planned，感谢反馈
