### ISSUE TITLE
试了好几次了

### ISSUE THREAD

**Issue by edenwyd2009** [Hex-Dragon/PCL2#3525]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

PCL找到了一个可疑的关键词：spongepowered

### PCL 错误报告、日志与附件

[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/14614863/Log1.txt)

### HMCL 启动脚本

[Uploading PCL 启动器日志.txt…]()

**Comment by allMagicNB** [comment]
你的 HMCL 启动脚本并未正确上传……

**Comment by rumengchuxing062** [comment]
根据日志信息，这似乎是登录失败造成的
返回信息是：```无效的 AccessToken，请重新登```
你应当尝试重新登录

**Comment by allMagicNB** [comment]
你这是网易的 Java 启动了……

**Comment by wuliaodexiaoluo** [comment]
```forge-1.16.5-36.2.41-client.jar```
Forge 有需要这个 Mod 码？
```spongepowered```
这又是什么加载器
另外日志大部分启动失败是依赖缺失问题

**Comment by kong-que-dnf123** [comment]
~好好好这怎么是个插件加载器还是啥玩意(?)~
![image](https://github.com/Hex-Dragon/PCL2/assets/120994373/58c01122-1706-4a70-a160-6dfdad3b10b2)

**Comment by liubanlaobanzhang** [comment]
spongepowered？
检查钠兼容性（这我可太熟悉了

**Comment by KLONOA9X6** [comment]
就是炸Mixin了
forge的mixin就算Sponge来的

**Comment by KLONOA9X6** [comment]
根据日志，注入失败的是这个模组：[MCPitanLibarch/MCPitanLib](https://www.mcmod.cn/class/8405.html)
```
[19:22:46] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed mcpitanlib-common.mixins.json:BlockMixin -> net.minecraft.block.Block: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on inject_onPlaced could not find any targets matching 'onPlaced' in net.minecraft.block.Block. No refMap loaded. [PREINJECT Applicator Phase -> mcpitanlib-common.mixins.json:BlockMixin -> Prepare Injections ->  -> handler$zeo000$inject_onPlaced(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/BlockState;Lnet/minecraft/entity/LivingEntity;Lnet/minecraft/item/ItemStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on inject_onPlaced could not find any targets matching 'onPlaced' in net.minecraft.block.Block. No refMap loaded. [PREINJECT Applicator Phase -> mcpitanlib-common.mixins.json:BlockMixin -> Prepare Injections ->  -> handler$zeo000$inject_onPlaced(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/BlockState;Lnet/minecraft/entity/LivingEntity;Lnet/minecraft/item/ItemStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_60] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_60] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_60] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60] {}
	at net.minecraftforge.registries.GameData.init(GameData.java:133) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:118) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.Registry.forge(Registry.java:347) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:access.RegistryAccess,pl:mixin:A}
	at net.minecraft.util.registry.Registry.forge(Registry.java:331) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:access.RegistryAccess,pl:mixin:A}
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:140) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:access.RegistryAccess,pl:mixin:A}
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) ~[?:?] {re:classloading}
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60] {}
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_60] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_60] {}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60] {}
```

**Comment by allMagicNB** [comment]
那关了吧……看 Author 反馈交完就跑，错误报告、日志、HMCL 的启动脚本就交个日志，之后还得有人一步步辅导他交这些材料……
既然现在还有可以直接确定的原因，那关了？
¯\\_(ツ)\_/¯
