### ISSUE TITLE
离线登录生成的启动脚本在高版本可能导致生成的启动脚本无法使用

### ISSUE THREAD

**Issue by mc-124** [Hex-Dragon/PCL2#3612]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

因为PCL2在启动脚本中使用X去给uuid打码，而X不是有效的hex数字，导致游戏报错`Invalid UUID string`

### 重现步骤

1.20.4离线启动+启动脚本=`Invalid UUID string`

### 日志与附件

这个就不需要PCL2日志了吧……
启动脚本输出：
```
游戏正在启动，请稍候。
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
        at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.NumberFormatException: Error at index 5 in: "00000XXX"
        at java.base/java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:83)
        at java.base/java.lang.Long.parseLong(Long.java:790)
        at java.base/java.util.UUID.fromString1(UUID.java:285)
        at java.base/java.util.UUID.fromString(UUID.java:260)
        at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
        at net.minecraft.client.main.Main.main(SourceFile:151)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
游戏已退出。
请按任意键继续. . .
```

**Comment by JingHai-Lingyun** [comment]
#3343

**Comment by LTCatt** [comment]
现在不再会给 UUID 打码，且如果 AccessToken 和 UUID 一样也不会给 AccessToken 打码

**Comment by LTCatt** [comment]
你的解锁码：wiFzPRLI4fRyDbfLhxCssa+twS6FO2G+
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by mc-124** [comment]
换机了，再给个码？
C061-3921-7448-5D35
