### ISSUE TITLE
为版本选择自定义 Logo 时报错

### ISSUE THREAD

**Issue by Moe23333** [Hex-Dragon/PCL2#368]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

提前将 `Logo.png` 文件复制至 `version/[version_name]/PCL` 文件夹内后，发现 PCL 没有自动识别并使用该 Logo，于是改用手动选择，并在选择该 Logo 时报错。

### 重现步骤

1. 点击`版本设置`
2. 选择`版本图标`-`自定义`
3. 选择已提前复制至 `version/[version_name]/PCL` 文件夹内的版本图标 `Logo.png`
4. 报错

### 日志与附件

Log
```
[20:44:36.927] [Start] 程序版本：Release 2.4.2（268）
[20:44:36.928] [Start] 识别码：6214-E6F3-D77E-CB9C
[20:44:36.928] [Start] 程序路径：D:\Program Files\PCL\Plain Craft Launcher 2.exe
[20:44:36.932] [Start] 第一阶段加载用时：32 ms
[20:44:37.074] [Loader] 加载器 Minecraft Folder List 状态改变：Loading
[20:44:37.075] [Start] 第二阶段加载用时：140 ms
[20:44:37.081] [Loader] 加载器 Minecraft Folder List 状态改变：Finished
[20:44:37.202] [Start] 加载 DLL：Json
[20:44:37.202] [System] 获取资源：Json
[20:44:37.268] [Java] 缓存中有 2 个可用的 Java
[20:44:37.296] [System] 窗口已置顶，位置：(315, 176), 810 x 500
[20:44:37.300] [Animation] 动画线程开始
[20:44:37.300] [Start] 第三阶段加载用时：110 ms
[20:44:37.306] [Launch] Minecraft 文件夹：D:\Program Files\PCL\.minecraft\
[20:44:37.353] [Loader] 加载器 Loader Skin Legacy 状态改变：Loading
[20:44:37.356] [Loader] 加载器 Loader Skin Legacy 状态改变：Finished
[20:44:37.377] [Minecraft] 启动按钮：Minecraft 版本：D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\
[20:44:37.381] [Loader] 加载器 登录 状态改变：Loading
[20:44:37.383] [Launch] 登录加载已开始
[20:44:37.385] [Loader] 加载器 Loader Login Legacy 状态改变：Loading
[20:44:37.386] [Launch] 登录方式：离线（Moe23333）
[20:44:37.387] [Loader] 加载器 Loader Login Legacy 状态改变：Finished
[20:44:37.388] [Skin] 载入头像成功：Loader Skin Legacy
[20:44:37.404] [Launch] 登录加载已结束
[20:44:37.404] [Loader] 加载器 登录 状态改变：Finished
[20:44:37.510] [Loader] 加载器 DlClientList Mojang 状态改变：Loading
[20:44:37.510] [Loader] 加载器 PCL2 服务 状态改变：Loading
[20:44:37.511] [Server] 正在连接到 PCL2 服务器
[20:44:37.513] [Net] 获取网络结果：https://launchermeta.mojang.com/mc/game/version_manifest.json，最大超时 10000
[20:44:37.515] [Net] 获取网络结果：http://pcl2-server-1253424809.file.myqcloud.com/notice.cfg?sign=1668170678-66b7b1a5-0-c8b817b2de46505a93f091cf8daffa33，最大超时 10000
[20:44:37.933] [System] DPI：192，工作区尺寸：2880 x 1704，系统版本：10.0.22623.0
[20:44:38.038] [Loader] 加载器 DlClientList Mojang 状态改变：Finished
[20:44:38.045] [Server] 服务器公告：83|269|268|4，无需更新
[20:44:38.049] [Loader] 加载器 PCL2 服务 状态改变：Finished
[20:44:38.647] [Control] 按下按钮：版本设置
[20:44:38.717] [Control] 切换主要页面：VersionSetup, 0
[20:45:08.285] [UI] 选择文件返回：D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png
[20:45:08.289] 更改自定义版本图标失败（quilt-loader-0.18.1-beta.10-1.18.2）：复制文件出错：D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png -> D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png
Caused By: Could not find file 'D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png'.
   at PCL.ModBase.CopyFile(String FromPath, String ToPath)
   at PCL.PageVersionOverall.ComboDisplayLogo_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at PCL.ModBase.CopyFile(String FromPath, String ToPath)
错误类型：System.IO.FileNotFoundException
[20:45:08.324] [Control] 普通弹窗：出现错误
更改自定义版本图标失败（quilt-loader-0.18.1-beta.10-1.18.2）：复制文件出错：D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png -> D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png
Caused By: Could not find file 'D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png'.
   at PCL.ModBase.CopyFile(String FromPath, String ToPath)
   at PCL.PageVersionOverall.ComboDisplayLogo_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   at PCL.ModBase.CopyFile(String FromPath, String ToPath)
错误类型：System.IO.FileNotFoundException

是否反馈此问题？如果不反馈，这个问题可能永远无法得到解决！
[20:45:09.562] [Control] 按下按钮：反馈
[20:45:09.563] [Control] 普通弹框返回：1
[20:45:09.683] [System] 诊断信息：
操作系统：Microsoft Windows 11 Pro for Workstations
剩余内存：2634 M / 16109 M
DPI：192（200%）
MC 文件夹：D:\Program Files\PCL\.minecraft\
文件位置：D:\Program Files\PCL\
[20:45:09.683] [System] 执行外部命令：explorer.exe "D:\Program Files\PCL\PCL\"
[20:45:09.703] [System] 正在打开网页：https://github.com/Hex-Dragon/PCL2/issues/
[20:45:09.735] 加载位图失败（D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png）：Could not find file 'D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at PCL.MyBitmap..ctor(String FilePathOrResourceName)
错误类型：System.IO.FileNotFoundException
[20:45:09.735] 加载版本图标失败：Could not find file 'D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\PCL\Logo.png'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at PCL.MyBitmap..ctor(String FilePathOrResourceName)
   at PCL.MyListItem.AssetParameter(String value)
   at PCL.PageSelectRight.McVersionListItem(McVersion Version)
错误类型：System.IO.FileNotFoundException
[20:45:09.742] [Loader] 加载器 Minecraft Version List 状态改变：Loading
[20:45:09.746] [Minecraft] 文件夹列表变更，重载所有版本
[20:45:09.783] [Setup] 当前选择的 Minecraft 版本：quilt-loader-0.18.1-beta.10-1.18.2
[20:45:09.783] [Minecraft] 选择该文件夹储存的 Minecraft 版本：D:\Program Files\PCL\.minecraft\versions\quilt-loader-0.18.1-beta.10-1.18.2\
[20:45:09.783] [Loader] 加载器 Minecraft Version List 状态改变：Finished
[20:45:13.122] [System] 收到关闭指令
[20:45:13.408] [System] 程序已退出，返回值：Success
```
![image](https://user-images.githubusercontent.com/35591595/201341661-4bd9a6cb-515d-4962-b1c5-96f9a4d464f8.png)
![image](https://user-images.githubusercontent.com/35591595/201341812-0c1c2819-8098-402a-b861-aa7e03d9bb38.png)
![image](https://user-images.githubusercontent.com/35591595/201342011-7883c1c5-d7b9-4e08-b39d-742cba41ba81.png)

**Comment by LTCatt** [comment]
额，我修了这个 Bug，但是我觉得更大的问题是为啥它会不识别这个 Logo……
那张图片传一下？

**Comment by Moe23333** [comment]
> 额，我修了这个 Bug，但是我觉得更大的问题是为啥它会不识别这个 Logo…… 那张图片传一下？

是 Quilt 的 Logo
![Logo](https://user-images.githubusercontent.com/35591595/201457650-98df9caf-fc0e-4807-bc93-a830ac8cf85b.png)

**Comment by Moe23333** [comment]
![image](https://user-images.githubusercontent.com/35591595/201457928-5b64c95f-b359-4bec-8705-6dd6313a2a06.png)
而且 PCL 似乎不能识别 Quilt：它将 Quilt 识别为了 Fabric 并使用 Fabric Logo（所以我才想要手动替换 Logo）
