### ISSUE TITLE
“在结束后开始音乐播放” 可能出错

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#3708]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/463c5901-c739-4e74-95e4-0be8cbc5ea6a)

### 重现步骤

别人做了个客户端，每次加载完成进入世界的时候直接报错

### 日志与附件

[Log2.txt](https://github.com/Hex-Dragon/PCL2/files/15048222/Log2.txt)
[Log3.txt](https://github.com/Hex-Dragon/PCL2/files/15048223/Log3.txt)
[Log4.txt](https://github.com/Hex-Dragon/PCL2/files/15048224/Log4.txt)
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15048225/Log5.txt)
[Log.txt](https://github.com/Hex-Dragon/PCL2/files/15048226/Log.txt)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15048227/Log1.txt)
[hs_err_pid8132.log](https://github.com/Hex-Dragon/PCL2/files/15048230/hs_err_pid8132.log)

**Comment by wuwenjun9939** [comment]
okok

**Comment by hejiehao** [comment]
有没有人把这个标题改掉……

**Comment by wuwenjun9939** [comment]
OK了不？

> okok

**Comment by wuwenjun9939** [comment]
> 有没有人把这个标题改掉……

OK了不？

**Comment by WorldHim** [comment]
进入世界崩溃与 PCL 的报错貌似是两个不同的问题
前者似乎是内存溢出导致的，你可以尝试调大内存分配与虚拟内存

**Comment by wuwenjun9939** [comment]
跟上次龙猫说的无法解决的问题一模一样（而且，我好像找到解决方法了）

> 进入世界崩溃与 PCL 的报错貌似是两个不同的问题 前者似乎是内存溢出导致的，你可以尝试调大内存分配与虚拟内存

**Comment by wuwenjun9939** [comment]
内存不足（偶尔的时候）的解决方法：检测C盘是否空间不足（我内存总是8.*，而且，我设置的是8gb），如果C盘空间不足，尝试删除%temp%文件夹的所有文件，如果不可以，崩溃并放出消息：无法加载游戏，因为你电脑的C盘空间不足，请尝试清理

**Comment by hejiehao** [comment]
TotalPageFile size 20290M (AvailPageFile size 31M)

**Comment by wuwenjun9939** [comment]
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/db971bf8-30e1-4c93-8ae3-ab964d9a0bf8)
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/e3908bbd-be00-41d6-a6cd-808e3828f618)
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/5be7002f-1804-49bf-aeb6-722903ddd4ff)

**Comment by wuwenjun9939** [comment]
> 内存不足（偶尔的时候）的解决方法：检测C盘是否空间不足（我内存总是8.*，而且，我设置的是8gb），如果C盘空间不足，尝试删除%temp%文件夹的所有文件，如果不可以，崩溃并放出消息：无法加载游戏，因为你电脑的C盘空间不足，请尝试清理

如果清理成功，内存迟迟不退，崩溃：无法加载游戏，虽然内存（硬盘）清理成功，但是，内存太高，请关闭不需要的软件并重试

**Comment by wuwenjun9939** [comment]
睡了，啥事明天上来看

**Comment by LTCatt** [comment]
```
[20:37:12.050] [Music] 已根据设置，在结束后开始音乐播放
[20:37:12.050] Runtime Invoke 9529#：线程执行失败：Object reference not set to an instance of an object.
   at Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.CallMethod(Container BaseReference, String MethodName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, BindingFlags InvocationFlags, Boolean ReportErrors, ResolutionFailure& Failure)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at PCL.ModMusic._Closure$__._Lambda$__14-0()
   at PCL.ModBase._Closure$__117-0._Lambda$__0()
错误类型：System.NullReferenceException
```

音乐播放相关

**Comment by allMagicNB** [comment]
> 我好几个issues了吧？要一个主题不过分吧？
> 8B36-C5D2-5E77-0B51

![Screenshot_20240523_193007_com.github.android.jpg](https://github.com/Hex-Dragon/PCL2/assets/116283787/8fd533b0-bd0c-48f1-a0b0-ce7f90d70bbf)

**Comment by wuwenjun9939** [comment]
> > 我好几个issues了吧？要一个主题不过分吧？
> > 8B36-C5D2-5E77-0B51
> 
> ![Screenshot_20240523_193007_com.github.android.jpg](https://private-user-images.githubusercontent.com/116283787/333164521-8fd533b0-bd0c-48f1-a0b0-ce7f90d70bbf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjQ2ODYsIm5iZiI6MTcxNjQ2NDM4NiwicGF0aCI6Ii8xMTYyODM3ODcvMzMzMTY0NTIxLThmZDUzM2IwLWJkMGMtNDhmMS1hMGIwLWNlN2Y5MGQ3MGJiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMTM5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDZjMWZmNzE3MWI3NDlhYTNiNTcxODA5Y2JjMGZkMTk3ZGQ3NGRiYzEyOGM4NmQwZmIzZTVmNjUyODIyNzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eHaWE2WAr0e8yj1XDLUUtHWC0kltvB57MZVDIGKR74s)

至少这个issues还在啊

**Comment by LTCatt** [comment]
需要一个 `已完成` 的 issue 才会给码，抱歉

**Comment by wuwenjun9939** [comment]
> 需要一个 `已完成` 的 issue 才会给码，抱歉

没事，你接着修吧（GitHub应该没有狗头表情）

**Comment by allMagicNB** [comment]
> 至少这个issues还在啊

你为什么要给 Issue 搞成复数形式？

**Comment by allMagicNB** [comment]
> > > 至少这个issues还在啊
> > 
> > 你为什么要给 Issue 搞成复数形式？
> 
> ![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/2ecb2e16-4b8a-4286-9cc6-e19a88e10a11)
> 

这是这个板块的名字，因为里边有很多的 Issue，所以才是负数形式

**Comment by wuwenjun9939** [comment]
> > > > 至少这个issues还在啊
> > > 
> > > 
> > > 你为什么要给 Issue 搞成复数形式？
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/110022109/333187552-2ecb2e16-4b8a-4286-9cc6-e19a88e10a11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Njg5NjUsIm5iZiI6MTcxNjQ2ODY2NSwicGF0aCI6Ii8xMTAwMjIxMDkvMzMzMTg3NTUyLTJlY2IyZTE2LTRiOGEtNDI4Ni05Y2M2LWUxOWE4OGUxMGExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMjUxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDRhODZjMTg0ZmMyYzM5MGY1ODhkZWIxZDA1MTY2Nzk1YjYwNGRmMTZkM2QxZGExYzVmOGIzMjRmYzg0YjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DoDNDZeM3B6YYYkkQHSgdCT28f8rezzlhvLjEDDJPV8)
> 
> 这是这个板块的名字，因为里边有很多的 Issue，所以才是复数形式

好吧，不过，我确实提交过很多的issue，虽然都是重复的（还有俩忽略）

**Comment by LTCatt** [comment]
关于结束后开始音乐播放，无法复现，也不知道咋回事，盲修了一下加了点 log，如果下个版本复发再说……
至于内存不足，你可以看看页面文件设置（虚拟内存）？

**Comment by LTCatt** [comment]
你的解锁码：Lx6f+kgz7SQjTVkksuuzPkxeX8oaiFDi
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by wuwenjun9939** [comment]
> 关于结束后开始音乐播放，无法复现，也不知道咋回事，盲修了一下加了点 log，如果下个版本复发再说…… 至于内存不足，你可以看看页面文件设置（虚拟内存）？

我看了，虚拟内存的设置是默认的....

**Comment by wuwenjun9939** [comment]
新版本解锁码：202F-E9D7-AF62-4525
帮个忙呗

**Comment by LTCatt** [comment]
你的解锁码：sx0oDGfMGZ8Aj+8QV/VLk4q5iXl30KyG
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by wuwenjun9939** [comment]
那么.......我又来了，没错，这回要更新码......（.更新 202F-E9D7-AF62-4525）

**Comment by wuliaodexiaoluo** [comment]
>那么.......我又来了，没错，这回要更新码......（.更新 202F-E9D7-AF62-4525）

更新麻烦去 [爱发电私信页面](https://afdian.com/message) 私信龙猫，会自动发更新密钥

**Comment by wuwenjun9939** [comment]
> > 那么.......我又来了，没错，这回要更新码......（.更新 202F-E9D7-AF62-4525）
> 
> 更新麻烦去 [爱发电私信页面](https://afdian.com/message) 私信龙猫，会自动发更新密钥

这个快照版是送的......

**Comment by wuyuncheng-26** [comment]
送的？？？？？
你朋友给你发的吗
这玩意可不能随便泄露啊

**Comment by wuliaodexiaoluo** [comment]
>送的？？？？？
你朋友给你发的吗
这玩意可不能随便泄露啊

其实还有一种可能，就是他朋友赞助了 54.32？

**Comment by bmmNbhjd** [comment]
https://github.com/Hex-Dragon/PCL2/discussions/3694#discussioncomment-9151723

**Comment by wuwenjun9939** [comment]
我怎么觉得.....龙猫不怎么看旧的issue.....（尤其是这种已经Closed的）

**Comment by JingHai-Lingyun** [comment]
@wuwenjun9939 如有需要，请让你的朋友帮你获取更新码，不要在这里回复，谢谢。

**Comment by SALTWOOD** [comment]
> 我怎么觉得.....龙猫不怎么看旧的issue.....（尤其是这种已经Closed的）

即使是重复、忽略、已经关闭的 issue，只要有回复都是会在 notification 里头显示的，所以在哪里都一样
更新码一般只需要获取一次；既然是你朋友送的，让他帮忙一次就行了

**Comment by Joining2843** [comment]
加没加自然音效

**Comment by wuliaodexiaoluo** [comment]
> 加没加自然音效

请不要在已关闭的 issue 下回复无关内容，如果您有需要某项 PCL 不支持的功能，请开一个新 issue

>[!IMPORTANT]
>
>请在提交 issue 时进行查重

**Comment by LTCatt** [comment]
https://github.com/Hex-Dragon/PCL2/issues/4402#issuecomment-2624553254
> 发现了一个可以 100% 复现的方法……
> 
> 在 PCL 播放音乐时，打开声音设置，然后禁用当前的输出设备（拔出设备也是相同的效果）。
> 
> 此时，PCL 的播放进度条会卡住不动，无论如何点击音乐图标也不会发出声音（如本 Issue 附件视频中所示）。 再搭配上 `游戏退出后自动开始播放` 这一功能，Minecraft 退出后 PCL 就会爆出 `System.NullReferenceException`。
> 
> 相关 Log：[Log1.txt](https://github.com/user-attachments/files/18603087/Log1.txt)
> 
> 注：怀疑与 [#3908](https://github.com/Hex-Dragon/PCL2/issues/3908) 为相同成因 又注：上述复现步骤与 [#480](https://github.com/Hex-Dragon/PCL2/issues/480) 大致相同
