### ISSUE TITLE
无法从新版本发布提示中直接下载新版本

### ISSUE THREAD

**Issue by U3L6** [Hex-Dragon/PCL2#3742]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

此问题已多次出现。当出现新版本发布提示之后，按下“下载”按钮，有可能不开始下载，无事发生，也有可能出现错误提示并弹窗。如果之后自己手动下载新版本，则不会出现问题，能正常下载和启动。我在国外，应该不是网络的问题

### 重现步骤

当出现新版本发布提示之后，按下“下载”按钮

### 日志与附件

![Screenshot 2024-04-26 175950](https://github.com/Hex-Dragon/PCL2/assets/75152141/1cd8e8ef-b991-416e-90cf-48e11380a191)
[Log1.txt](https://github.com/Hex-Dragon/PCL2/files/15136227/Log1.txt)

**Comment by allMagicNB** [comment]
你打开下这个试试
https://launchermeta.mojang.com/mc/game/version_manifest.json

**Comment by U3L6** [comment]
> 你打开下这个试试 https://launchermeta.mojang.com/mc/game/version_manifest.json

打得开

**Comment by U3L6** [comment]
[version_manifest.json](https://github.com/Hex-Dragon/PCL2/files/15136255/version_manifest.json)

**Comment by JingHai-Lingyun** [comment]
这是 “未将对象设置到引用对象的的实例” 的英文体现...

**Comment by allMagicNB** [comment]
这里加个中文报错，以方便查重（
可视化安装版本列表出错：未将对象引用设置到对象的实例。

**Comment by U3L6** [comment]
刚才1.20.6更新提示出来，pcl2再次弹窗，弹窗时主窗口卡在页面切换动画不动。关闭弹窗后pcl2直接崩溃（回桌面）。我没截屏。话说这问题出现好多次了怎么只有我反馈

**Comment by LTCatt** [comment]
我自己没法复现，但对着日志修了一个潜在的问题，不知道是不是这个引起的 =。=
如果更新之后依然有问题再 Reopen 吧……

**Comment by U3L6** [comment]
> 我自己没法复现，但对着日志修了一个潜在的问题，不知道是不是这个引起的 =。= 如果更新之后依然有问题再 Reopen 吧……

那我的活跃橙主题:)

**Comment by U3L6** [comment]
61AC-ECC9-B5DF-A93E

**Comment by LTCatt** [comment]
你的解锁码：4AVRGkpshHp2IPV27RhCgoyzEM1ZVSeW
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by U3L6** [comment]
> 我自己没法复现，但对着日志修了一个潜在的问题，不知道是不是这个引起的 =。= 如果更新之后依然有问题再 Reopen 吧……

最新的快照启动器仍存在该问题，触发条件和原来一样
![image](https://github.com/Hex-Dragon/PCL2/assets/75152141/ae297006-aebe-4520-b7e3-c24cddf8c0ee)

**Comment by U3L6** [comment]
[Log5.txt](https://github.com/Hex-Dragon/PCL2/files/15342479/Log5.txt)

**Comment by JingHai-Lingyun** [comment]
```
# Ln 1
[18:01:29.679] [Start] 程序版本：Snapshot 2.7.2 (322)
# Ln 97
[18:01:33.496] 程序出现未知错误：Object reference not set to an instance of an object.
   at PCL.PageDownloadInstall.SelectReload()
   at PCL.PageDownloadInstall.Init()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
错误类型：System.NullReferenceException
```
Reopen

**Comment by U3L6** [comment]
最新版问题仍存在

**Comment by LTCatt** [comment]
因为还是复现不出来，又盲修了个疑似导致出错的原因……希望这次能行（悲

**Comment by U3L6** [comment]
这次可以了:)
