### ISSUE TITLE
自动选择java游戏崩溃

### ISSUE THREAD

**Issue by aisiweer** [Hex-Dragon/PCL2#411]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

自动选择适合游戏版本的,但是java版本过高游戏崩溃

### 错误报告、日志与附件

[错误报告-2022-11-19_10.27.47.zip](https://github.com/Hex-Dragon/PCL2/files/10045897/-2022-11-19_10.27.47.zip)

**Comment by LTCatt** [comment]
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more

**Comment by HowardZHY** [comment]
类似的，15w14a fabric也会误判使用java17

**Comment by aisiweer** [comment]
292A-5C00-940A-15BD

**Comment by LTCatt** [comment]
你的解锁码：ouArJWU2gpm+VP4PQRkLXO8XLAjgZho9
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

**Comment by aisiweer** [comment]
重装系统了 求重新给解锁码（  E278-4488-52B2-5FEC

**Comment by LTCatt** [comment]
你的解锁码：ytBAB2/nY3xMqINXIyXJDp+e2GRb3Obe
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
