### ISSUE TITLE
加载线程 等待游戏窗口出现 (25) 发生运行时错误：$$

### ISSUE THREAD

**Issue by wuwenjun9939** [Hex-Dragon/PCL2#4111]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[19:15:11.700] [Crash] 以下为游戏输出的最后一段内容：
Exception in thread "main" java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:68)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)****

### PCL 错误报告、日志与附件

[里面自带启动脚本（powershell版本）.zip](https://github.com/user-attachments/files/16012601/-2024-6-27_19.15.16.zip)

### HMCL 启动脚本

略（看上面）

**Comment by wuwenjun9939** [comment]
pcl日志：
[Log2.txt](https://github.com/user-attachments/files/16012619/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16012620/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16012621/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16012622/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/16012624/Log.txt)
[Log1.txt](https://github.com/user-attachments/files/16012625/Log1.txt)

**Comment by allMagicNB** [comment]
HMCL 能启动？

**Comment by wuwenjun9939** [comment]
> HMCL 能启动？

我也不确定

**Comment by allMagicNB** [comment]
你不确定你先试试啊

**Comment by wuwenjun9939** [comment]
测试完成，无法打开
![image](https://github.com/Hex-Dragon/PCL2/assets/110022109/d8822fbc-abc0-4047-803f-ca10cf44e2ca)

**Comment by wuwenjun9939** [comment]
测试完成，复现方法：先在pcl安装一个forge的任意版本，之后用hmcl安装任意opt，导致启动失败（怀疑是两个启动器的文件问题）

**Comment by allMagicNB** [comment]
那是 HMCL 的问题

**Comment by wuwenjun9939** [comment]
> 那是 HMCL 的问题

好吧

**Comment by JingHai-Lingyun** [comment]
不要用 HMCL 修改由 PCL 安装的版本，已知外部修改会导致 PCL 启动失败
