### ISSUE TITLE
极小几率下未出现 Minecraft 窗口，但提示启动成功

### ISSUE THREAD

**Issue by PhantomPixel-0418** [Hex-Dragon/PCL2#4375]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

![屏幕截图 2024-07-30 084752](https://github.com/user-attachments/assets/73cb69d0-a914-45a8-944f-e376c49aadd7)
如图，这里pcl右下角是有关闭Minecraft的按钮的（上图为8:47分截图）

### 重现步骤

1、启动游戏
2、就卡了（极小几率）

### 日志与附件

[Log2.txt](https://github.com/user-attachments/files/16420519/Log2.txt)
尝试再现但再现失败

**Comment by PhantomPixel-0418** [comment]
就很无语，尝试下能不能再现，日志也体现不出啥，就java弹了个提示，pcl这边也没有相应的提示

**Comment by allMagicNB** [comment]
上传 Log3.

**Comment by wuyuncheng-26** [comment]
有其他的日志吗？
就一个日志看不出什么的

**Comment by youzi-2333** [comment]
```
[08:54:09.896] [Launch] [25792] 日志 3/5：LWJGL 版本已确认
[08:54:10.138] [Launch] [25792] Minecraft 窗口已加载：Minecraft* 1.20.4（1574906）
[08:54:11.055] [Launch] [25792] Minecraft 加载已完成
[08:54:11.132] [Loader] 加载器 等待游戏窗口出现 状态改变：Finished
[08:54:11.157] [Loader] 加载器 结束处理 状态改变：Loading
[08:54:11.157] [Loader] 加载线程 结束处理 (3) 已启动
[08:54:11.159] [Launch] 开始启动结束处理
[08:54:11.159] [Launch] 启动器可见性：5
[08:54:11.159] [Loader] 加载器 结束处理 状态改变：Finished
[08:54:11.239] [Loader] 加载器 Minecraft 启动 状态改变：Finished
[08:54:11.239] [Taskbar] Minecraft 启动 已移出任务列表
[08:54:11.522] [Loader] 加载器 Loader Launch 状态改变：Finished
[08:54:11.522] [UI] 弹出提示：1.20.4-Fabric 0.15.11-OptiFine_I7 启动成功！
[08:54:22.798] [Launch] [25792] 日志 4/5：OpenAL 已加载
[08:54:23.027] [Launch] [25792] 日志 5/5：材质已加载
[08:54:30.616] [Launch] [25792] Minecraft 已退出，返回值：0
[08:54:30.618] [Launch] [全局] 已无运行中的 Minecraft
[08:54:30.846] [Launch] [25792] Minecraft 日志监控已退出
```

应该是 MC 窗口出来了，但是过了几秒又退出了，不知道啥原因。

而且这个日志不是 08:47 的……

**Comment by PhantomPixel-0418** [comment]
[Log3.txt](https://github.com/user-attachments/files/16420589/Log3.txt)

**Comment by wuyuncheng-26** [comment]
`[08:47:32.134] [Launch] 实际的错误信息：对路径“D:\pcl\.minecraft\versions\1.20.4-Fabric 0.15.11-OptiFine_I7\1.20.4-Fabric 0.15.11-OptiFine_I7-natives\glfw.dll”的访问被拒绝。：PCL 的权限不足。请尝试右键 PCL，选择以管理员身份运行。`

**Comment by PhantomPixel-0418** [comment]
那我之前都行（？

**Comment by wuyuncheng-26** [comment]
你还有其他的 Log 文件吗
都上传上来看看

**Comment by PhantomPixel-0418** [comment]
log1是我尝试再现的，但是没有再现成功
[Log1.txt](https://github.com/user-attachments/files/16420601/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16420602/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16420603/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16420604/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16420605/Log5.txt)

**Comment by allMagicNB** [comment]
#3782？

**Comment by PhantomPixel-0418** [comment]
我在中途没取消

**Comment by JingHai-Lingyun** [comment]
类似 #4371，请上传你的 Minecraft 日志（即使 Minecraft 没有崩溃）

**Comment by allMagicNB** [comment]
> 我在中途没取消

你放屁
![Screenshot_20240730_091830_bin.mt.plus.jpg](https://github.com/user-attachments/assets/1eac553a-a90f-4dfe-b00e-c561d02def43)

**Comment by PhantomPixel-0418** [comment]
> > 我在中途没取消
> 
> 你放屁 ![Screenshot_20240730_091830_bin.mt.plus.jpg](https://private-user-images.githubusercontent.com/116283787/353278020-1eac553a-a90f-4dfe-b00e-c561d02def43.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDI2NzUsIm5iZiI6MTcyMjMwMjM3NSwicGF0aCI6Ii8xMTYyODM3ODcvMzUzMjc4MDIwLTFlYWM1NTNhLWE5MGYtNGRmZS1iMDBlLWM1NjFkMDJkZWY0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMTE5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODZiMDJiZDIxZDMzY2QzZGMyNTA1OGU0MGVkNTIzZjBhNDkzMThjM2ZhYTUyOWFmNjk5NDdlZTE3MDQyMmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f83NymbGEcEgVA-mPW6Z4wWi5GU3wbr-ZrtZf3XpgAE)

哥们，我是启动成功之后关的

**Comment by wuyuncheng-26** [comment]
？你再复现一次
很有可能是你的错误操作导致的

**Comment by PhantomPixel-0418** [comment]
是不是因为我按了睡眠🫠🫠

**Comment by allMagicNB** [comment]
> 哥们，我是启动成功之后关的

你要不要好好看看#3782

**Comment by JingHai-Lingyun** [comment]
上传你的 Minecraft 日志，怀疑是有什么模组拦截了 Minecraft 的启动

**Comment by PhantomPixel-0418** [comment]
Minecraft 是哪个文件夹的（雾

**Comment by PhantomPixel-0418** [comment]
.minecraft\logs是吧

**Comment by PhantomPixel-0418** [comment]
[2024-07-30-1.log.gz](https://github.com/user-attachments/files/16420644/2024-07-30-1.log.gz)
[2024-07-30-2.log.gz](https://github.com/user-attachments/files/16420642/2024-07-30-2.log.gz)
[2024-07-30-3.log.gz](https://github.com/user-attachments/files/16420645/2024-07-30-3.log.gz)

**Comment by PhantomPixel-0418** [comment]
应该是2，2的日期是47分的

**Comment by wuyuncheng-26** [comment]
```
[08:47:23] [Render thread/WARN]: Failed to create window: 
net.minecraft.class_1041$class_4716: GLFW error 65544: WGL: Failed to make dummy context current: 找不到指定的程序。 
	at net.minecraft.class_1041.method_4501(class_1041.java:256) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229) ~[lwjgl-glfw-3.3.2.jar:?]
	at net.minecraft.class_1041.<init>(class_1041.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_3682.method_16038(class_3682.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(Unknown Source) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-Fabric%200.15.11-OptiFine_I7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
```

**Comment by PhantomPixel-0418** [comment]
看来我需要把 Dynamic FPS 删除，因为这有潜在的问题

**Comment by wuyuncheng-26** [comment]
找不到指定的程序?

**Comment by PhantomPixel-0418** [comment]
？我这有java
![image](https://github.com/user-attachments/assets/a796a296-5f1b-428f-8c4f-b8315282ddbb)

**Comment by PhantomPixel-0418** [comment]
？

**Comment by PhantomPixel-0418** [comment]
因为我自己再尝试了下，所以 `latest.log` 里面装的不是出现问题的

**Comment by JingHai-Lingyun** [comment]
你的 GL 出现了问题，但是在日志中没有找到让 Minecraft 崩溃的提示。
在这种情况下，类似 #4371 的，应该是没法检查了。但仍然挂在这里让龙猫看看，因为和那个还是有点区别

---

额外提示：
请不要连续发送短信息，Github 不是 SMS（即时通讯）工具。
连续发送信息会导致通知 Watch 了仓库的人收到大量邮件
![image](https://github.com/user-attachments/assets/276e8e74-b9f4-4b8f-bd0a-35b66367f3fb)
如果你想要修改信息，请点击信息右上角 `...` -> `Edit` 并在更改后点击绿色按钮保存。

**Comment by Pigeon0v0** [comment]
设备管理器 - 显示适配器 截个图

**Comment by PhantomPixel-0418** [comment]
> 设备管理器 - 显示适配器 截个图

![image](https://github.com/user-attachments/assets/909f4405-bbda-4030-a98f-ed0f8ca28fdf)
