### ISSUE TITLE
安装mcbbs整合包时可能会崩溃或者卡住或者安装失败

### ISSUE THREAD

**Issue by zyp114514** [Hex-Dragon/PCL2#4421]
### 检查项

- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是网络环境不佳[（解决方法）](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-0hDr)，并非 PCL 的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我知晓大多数此类问题都是网络环境不佳导致的，但我确实认为我的问题可能是 PCL 导致的，和网络环境无关。
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

安装mcbbs整合包很容易崩溃（停止运行）或者解压卡在2%

游戏安装失败
→ 下载 Forge 47.2.32失败
→ 安装 Forge（方式 A）失败
→ 安装新 Forge 版本失败
→ 运行 Forge 安装器失败
→ Forge 安装器出错，日志结束部分为：
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.bangbang93.ForgeInstaller.main(ForgeInstaller.java:72)
Failed to extract files from archive: 
  /data/client.lzma
false
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModLoader.LoaderTask`2._Closure$__13-0._Lambda$__0()
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)
   在 PCL.ModDownloadLib.ForgelikeInjector(String Target, LoaderTask`2 Task, String McFolder, Boolean UseJavaWrapper, Boolean IsNeoForge)
   在 PCL.ModDownloadLib._Closure$__35-0._Lambda$__7(LoaderTask`2 Task)

### 重现步骤

把modpack.zip拖进PCL窗口
modpack.zip: https://zyp1-my.sharepoint.com/:u:/g/personal/userzyp_zyp1_onmicrosoft_com/EZ6Wy671KyROpYDoZHL3MWgBhi1ZZ1ls2GaMMZNqR_5jSQ?e=QdvxK0

### 日志与附件

[Log1.txt](https://github.com/user-attachments/files/16505177/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16505178/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16505179/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16505180/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16505181/Log5.txt)
[Log.txt](https://github.com/user-attachments/files/16505182/Log.txt)

**Comment by zyp114514** [comment]
没事了原来是我c盘炸了
