### ISSUE TITLE
Minecraft 出现错误

### ISSUE THREAD

**Issue by wudiwudidream** [Hex-Dragon/PCL2#4515]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃基本不是 PCL 的原因，请 **不要** 提交反馈。你可以在论坛或社区找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用 HMCL 启动，HMCL 没有出现问题。** 如果 HMCL 也无法启动就不是 PCL 导致的问题，请 **不要** 提交反馈。[下载 HMCL](https://hmcl.huangyuhui.net/download)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 和 [常见&难检反馈及问题列表](https://github.com/Hex-Dragon/PCL2/discussions/1930) 中搜索，确认了这一 Bug 未被提交过。

### 描述

黑屏（或者说直接崩溃），但是这个是不确定的，已经获得错误的日志文件，此日志文件具有二进制，具体不知道什么意思

### PCL 错误报告、日志与附件

[s.txt](https://github.com/user-attachments/files/16636707/s.txt)

**Comment by allMagicNB** [comment]
没有错误报告？

**Comment by wuyuncheng-26** [comment]
你告诉我这是错误报告？
![image](https://github.com/user-attachments/assets/24cd95bb-b62c-4f9b-a1c5-5530525b3b9c)

**Comment by JingHai-Lingyun** [comment]
~~你这是把 TraceBack 导出来了吗？~~
请先在启动器 “Minecraft 出现错误” 页面点 “导出错误报告”，把完整的错误报告压缩文件发出来

**Comment by wudiwudidream** [comment]
> 没有错误报告？

有的

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/user-attachments/assets/fb8e2f32-b751-4057-b048-1bacca6ed3ae)
请上传这 5 个文件
以及 Minecraft 的错误报告

**Comment by JingHai-Lingyun** [comment]
上传错误报告

**Comment by wudiwudidream** [comment]
> ![图像](https://private-user-images.githubusercontent.com/122529705/358574027-fb8e2f32-b751-4057-b048-1bacca6ed3ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDk2MDIsIm5iZiI6MTcyMzgwOTMwMiwicGF0aCI6Ii8xMjI1Mjk3MDUvMzU4NTc0MDI3LWZiOGUyZjMyLWI3NTEtNDA1Ny1iMDQ4LTFiYWNjYTZlZDNhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMTU1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDg4ZjY3ZGNmOTU2YWUzYWI5Zjk3NTlkMTc5NTljZGFmMzJjZDJiYjY0NzgyODg5NWFhZjg3MzA2MzQzZTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VuvmrMqwV0jWpd1xgpwEuE-gESMigsYQqFORMYNkd1M) 请上传这 5 个文件 以及 Minecraft 的错误报告

我发的是崩溃文件，仅仅这一个日志（没有其他的，属实不知道什么意思）

**Comment by wudiwudidream** [comment]
这个是重现上次的情况

**Comment by hejiehao** [comment]
若你使用PCL2启动器，在游戏崩溃后在崩溃界面点左下角`导出错误报告`，把导出的压缩包整个发上来 ![Image](https://img.kookapp.cn/assets/2023-03/CqLof1HzCe0g405l.png)

**Comment by wudiwudidream** [comment]
> 上传错误报告

s.txt那个就是包含了错误报告

**Comment by JingHai-Lingyun** [comment]
请尝试再次引发崩溃，然后导出错误日志
![image](https://github.com/user-attachments/assets/5bd77e12-b754-45a7-a508-c14c458c6b77)
s.txt **不是**错误报告，看起来是堆栈报告

---

另请善用 Edit 功能，**不建议**短时间连续发送短信息

**Comment by wudiwudidream** [comment]
> 如果你使用PCL2启动器，在游戏崩溃后在崩溃界面点左下角`导出错误报告`，把导出的压缩包整个发上来![图像](https://camo.githubusercontent.com/74bde40aba49b0ae20bbbdcb047c2f1baf7c7821f325909c6dbc92498f83bcef/68747470733a2f2f696d672e6b6f6f6b6170702e636e2f6173736574732f323032332d30332f43714c6f6631487a436530673430356c2e706e67)

s.txt那里边有（再三强调，只有那一个错误报告）

**Comment by wuyuncheng-26** [comment]
> > 上传错误报告
> 
> s.txt那个就是包含了错误报告

你把整个 .zip 发上来不行么。。。

**Comment by wudiwudidream** [comment]
> > > 上传错误报告
> > 
> > 
> > s.txt那就包含了错误报告
> 
> 你把整个.zip发上来不了。。。

当时报错的时候游戏导出来的那个

**Comment by allMagicNB** [comment]
……你 PCL 的日志也没了？

**Comment by JingHai-Lingyun** [comment]
> s.txt那里边有（再三强调，只有那一个错误报告）

您可以自己打开那个文件看看吗？哪里有错误报告？
如果您无法找到错误报告压缩包，请上传你的 PCL 日志或再次引发崩溃后导出上传

**Comment by wuyuncheng-26** [comment]
你再去复现一遍
然后看到 PCL 的报错弹窗后点击 `导出错误报告`
然后把导出的整个 .zip 包发上来
~我已经说得很详细了，希望你能听懂~

**Comment by wudiwudidream** [comment]
> ……你PCL的日志也没了？

不是，游戏导出来的，有十进制代码，我去翻译一下

**Comment by hejiehao** [comment]
https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-fvZW

**Comment by wudiwudidream** [comment]
[Log1.txt](https://github.com/user-attachments/files/16636774/Log1.txt)
[Log2.txt](https://github.com/user-attachments/files/16636775/Log2.txt)
[Log3.txt](https://github.com/user-attachments/files/16636776/Log3.txt)
[Log4.txt](https://github.com/user-attachments/files/16636777/Log4.txt)
[Log5.txt](https://github.com/user-attachments/files/16636778/Log5.txt)

**Comment by wuliaodexiaoluo** [comment]
>不是，游戏导出来的，有十进制代码，我去翻译一下

有没有可能这是堆栈日志，还有十进制代码是什么鬼
不要把 GitHub 当 SMS，有话一次性说完谢谢

**Comment by wudiwudidream** [comment]
> > 不是，游戏归来的，有十个徒步代码，我去翻译一下
> 
> 有没有可能这是堆栈日志，还有十个开源代码是什么鬼 不要在发短信时把GitHub放到GitHub上，有话一次性说完谢谢 请善用编辑和隐藏功能
十进制

**Comment by wuyuncheng-26** [comment]
```
[13:59:34.255] [Download] 1.16.5-Forge_36.2.34.jar 7866#：出错，未能解析此远程名称: 'oba-potato-4.yeahfast.com'
你的网络环境不佳，导致难以连接到服务器。请检查网络，多重试几次，或尝试使用 VPN。
————————————
详细错误信息：
   在 PCL.ModNet.NetFile.Thread(NetThread Info)
错误类型：System.Net.WebException
```
是这个吗？
这不是 PCL 的问题啊

**Comment by wudiwudidream** [comment]
应该不是这个

**Comment by wudiwudidream** [comment]
> ```
> [13:59:34.255] [Download] 1.16.5-Forge_36.2.34.jar 7866#：出错，未能解析此远程名称: 'oba-potato-4.yeahfast.com'
> 你的网络环境不佳，导致难以连接到服务器。请检查网络，多重试几次，或尝试使用 VPN。
> ————————————
> 详细错误信息：
>    在 PCL.ModNet.NetFile.Thread(NetThread Info)
> 错误类型：System.Net.WebException
> ```
> 
> 是这个吗？ 这不是 PCL 的问题啊

麻烦查看一下s.txt那个是什么意思（日志）

**Comment by wuyuncheng-26** [comment]
那个是堆栈报告……
你当时传错了

**Comment by wudiwudidream** [comment]
> 那个是堆栈报告…… 你当时传错了

帮忙看一下出啥问题了

**Comment by wuyuncheng-26** [comment]
```
[16:56:09.279] [Control] 普通弹窗：Minecraft 出现错误
你的显卡驱动存在问题，导致游戏无法正常运行。

请尝试升级你的显卡驱动到最新版本，或回退到出厂版本，然后再启动游戏。
如果还是不行，可以尝试使用 8.0.51 或更低版本的 Java。
如果问题依然存在，那么你可能需要换个更好的显卡……
如果要寻求帮助，请向他人发送错误报告文件，而不是发送这个窗口的截图。
```
你显卡驱动的问题……
和 PCL 无关

**Comment by wudiwudidream** [comment]
> ```
> [16:56:09.279] [Control] 普通弹窗：Minecraft 出现错误
> 你的显卡驱动存在问题，导致游戏无法正常运行。
> 
> 请尝试升级你的显卡驱动到最新版本，或回退到出厂版本，然后再启动游戏。
> 如果还是不行，可以尝试使用 8.0.51 或更低版本的 Java。
> 如果问题依然存在，那么你可能需要换个更好的显卡……
> 如果要寻求帮助，请向他人发送错误报告文件，而不是发送这个窗口的截图。
> ```
> 
> 你显卡驱动的问题…… 和 PCL 无关

这个是上次的日志，主要是s.txt的那个

**Comment by JingHai-Lingyun** [comment]
<details>

<summary>崩溃日志详情（in Log5.txt）

2024-08-10 16:54:59,536 main WARN Advanced terminal features are not available in this environment
2024-08-10 16:54:59,637 main ERROR Unable to delete file C:\Users\atar\Desktop\PCL\.minecraft\logs\latest.log: java.nio.file.FileSystemException C:\Users\atar\Desktop\PCL\.minecraft\logs\latest.log: 另一个程序正在使用此文件，进程无法访问。

[16:54:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, wudiwudiDream, --version, 1.16.5-Forge, --gameDir, C:\Users\atar\Desktop\PCL\.minecraft, --assetsDir, C:\Users\atar\Desktop\PCL\.minecraft\assets, --assetIndex, 1.16, --uuid, 286096b30faf48b9b3565e317fcd3695, --accessToken, ????????, --userType, msa, --versionType, PCL, --width, 873, --height, 479, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.42, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[16:54:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_421 by Oracle Corporation
[16:55:01] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[16:55:01] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/atar/Desktop/PCL/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[16:55:04] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5-Forge, --gameDir, C:\Users\atar\Desktop\PCL\.minecraft, --assetsDir, C:\Users\atar\Desktop\PCL\.minecraft\assets, --uuid, 286096b30faf48b9b3565e317fcd3695, --username, wudiwudiDream, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, PCL, --width, 873, --height, 479]
[16:55:16] [Render thread/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:55:34] [Render thread/ERROR] [minecraft/Minecraft]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:125) ~[authlib-2.1.28.jar:?] {re:classloading}
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:94) ~[authlib-2.1.28.jar:?] {}
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?] {}
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_244735_a(Minecraft.java:551) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:imblocker:window_focus_asm,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:imblocker:window_focus_asm,pl:mixin:APP:tweakerge.mixins.json:MixinMinecraftClient,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient,pl:mixin:APP:win_kb_fix.forge.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:383) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:imblocker:window_focus_asm,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:imblocker:window_focus_asm,pl:mixin:APP:tweakerge.mixins.json:MixinMinecraftClient,pl:mixin:APP:mafglib.mixins.json:MixinMinecraftClient,pl:mixin:APP:win_kb_fix.forge.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.5-Forge.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_421] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.42.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_421] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?] {}
Caused by: java.net.UnknownHostException: api.minecraftservices.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_421] {}
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_421] {}
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_421] {}
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_421] {}
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_421] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_421] {}
	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:140) ~[authlib-2.1.28.jar:?] {}
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:104) ~[authlib-2.1.28.jar:?] {re:classloading}
	... 22 more
[16:55:34] [Render thread/INFO] [minecraft/Minecraft]: Setting user: wudiwudiDream
[16:55:35] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.2.2 build 10
[16:55:35] [modloading-worker-11/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 36.2.42, for MC 1.16.5 with MCP 20210115.111550
[16:55:35] [modloading-worker-2/INFO] [STDOUT/]: [yalter.mousetweaks.Logger:Log:6]: [Mouse Tweaks] Main.initialize()
[16:55:35] [modloading-worker-11/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v36.2.42 Initialized
[16:55:35] [modloading-worker-2/INFO] [STDOUT/]: [yalter.mousetweaks.Logger:Log:6]: [Mouse Tweaks] Reflecting GuiContainer...
[16:55:35] [modloading-worker-2/INFO] [STDOUT/]: [yalter.mousetweaks.Logger:Log:6]: [Mouse Tweaks] Detected obfuscation: FORGE.
[16:55:35] [modloading-worker-2/INFO] [STDOUT/]: [yalter.mousetweaks.Logger:Log:6]: [Mouse Tweaks] Success.
[16:55:35] [modloading-worker-2/INFO] [STDOUT/]: [yalter.mousetweaks.Logger:Log:6]: [Mouse Tweaks] Initialized.
[16:55:37] [Render thread/INFO] [mojang/NarratorWindows]: Narrator library for x64 successfully loaded
[16:55:37] [Render thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Mod Resources, Default, PureBDcraft 128x MC116.zip
[16:55:37] [modloading-worker-11/INFO] [io.gi.re.im.IMBlocker/]: imblock loading config
[16:55:37] [modloading-worker-11/WARN] [io.gi.re.im.IMBlocker/]: Class journeymap.client.ui.waypoint.WaypointEditor not found, ignored.
[16:55:37] [modloading-worker-11/WARN] [io.gi.re.im.IMBlocker/]: Class com.ldtteam.blockout.BOScreen not found, ignored.
[16:55:37] [modloading-worker-11/INFO] [io.gi.re.im.IMBlocker/]: imblocker bakelist screenWhitelist result [class net.minecraft.client.gui.screen.EditBookScreen, class net.minecraft.client.gui.screen.EditSignScreen]
[16:55:37] [modloading-worker-11/INFO] [io.gi.re.im.IMBlocker/]: imblocker bakelist screenBlacklist result []
[16:55:37] [modloading-worker-11/INFO] [io.gi.re.im.IMBlocker/]: imblocker bakelist inputWhitelist result []
[16:55:37] [modloading-worker-11/INFO] [io.gi.re.im.IMBlocker/]: imblocker bakelist inputBlacklist result []
[16:55:37] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [mousetweaks] Starting version check at http://play.sourceruns.org/yalter/MouseTweaks/update.json
[16:55:42] [Render thread/INFO] [minecraft/SoundSystem]: OpenAL initialized.
[16:55:42] [Render thread/INFO] [minecraft/SoundEngine]: Sound engine started
[16:55:42] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x128x0 jei:textures/atlas/gui.png-atlas
[16:55:42] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 8192x4096x4 minecraft:textures/atlas/blocks.png-atlas
[16:55:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 2048x1024x4 minecraft:textures/atlas/signs.png-atlas
[16:55:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 4096x4096x4 minecraft:textures/atlas/banner_patterns.png-atlas
[16:55:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 4096x4096x4 minecraft:textures/atlas/shield_patterns.png-atlas
[16:55:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 2048x2048x4 minecraft:textures/atlas/chest.png-atlas
[16:55:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 4096x2048x4 minecraft:textures/atlas/beds.png-atlas
[16:55:43] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 4096x2048x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[16:55:44] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 2048x1024x0 minecraft:textures/atlas/particles.png-atlas
[16:55:44] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 2048x2048x0 minecraft:textures/atlas/paintings.png-atlas
[16:55:44] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x0 minecraft:textures/atlas/mob_effects.png-atlas
[16:55:44] [Render thread/INFO] [co.jo.wi.Constants/]: Trying to disable sticky keys & hook keyboard
[16:55:46] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.lang.NullPointerException: null
	at net.minecraftforge.fml.VersionChecker$1.openUrlString(VersionChecker.java:160) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:187) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Unknown Source) [?:1.8.0_421] {}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [forge:?] {re:classloading}
[16:55:46] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[16:55:54] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: AHEAD Current: 36.2.42 Target: null
[16:56:03] [Render thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Mod Resources, Default
[16:56:05] [Render thread/INFO] [minecraft/SoundSystem]: OpenAL initialized.
[16:56:05] [Render thread/INFO] [minecraft/SoundEngine]: Sound engine started
[16:56:06] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x128x0 jei:textures/atlas/gui.png-atlas
[16:56:06] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[16:56:06] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[16:56:06] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[16:56:06] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[16:56:06] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[16:56:06] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[16:56:06] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8cd763365, pid=13088, tid=0x0000000000002e04
#
# JRE version: Java(TM) SE Runtime Environment (8.0_421) (build 1.8.0_421-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.421-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [atio6axx.dll+0x2153365]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\atar\Desktop\PCL\.minecraft\hs_err_pid13088.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed

</details>

根据现有日志判断，这个问题很大概率不是 PCL 引起的，先关了。
如果有需要，请前往 [Discussion 大区发帖提问](https://github.com/Hex-Dragon/PCL2/discussions/new?category=%E6%8F%90%E9%97%AE)，感谢合作。

**Comment by wudiwudidream** [comment]
> 崩溃日志详情（in Log5.txt）
> 根据现有日志判断，这个问题很大概率不是 PCL 引起的，先关了。 如果有需要，请前往 [Discussion 大区发帖提问](https://github.com/Hex-Dragon/PCL2/discussions/new?category=%E6%8F%90%E9%97%AE)，感谢合作。

好的，谢谢

**Comment by wuliaodexiaoluo** [comment]
>麻烦查看一下s.txt那个是什么意思（日志）

堆栈日志。。。。这谁看得懂啊

**Comment by wudiwudidream** [comment]
> > 麻烦查看一下s.txt那个是什么意思（日志）
> 
> 堆栈日志。。。。这谁看得懂啊

有十进制的那个东西对照一下英语（大概率是中文），对比一下就知道了

**Comment by JingHai-Lingyun** [comment]
请勿继续回复无关内容，感谢合作。
