### ISSUE TITLE
求助java好像出了问题，重装也没用

### ISSUE THREAD

**Issue by wdwdwas** [Hex-Dragon/PCL2#597]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\���\AppData\Local\Temp\libwrapper-1599703682714437805.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at oolloo.jlw.ArgLoader.loadNative(ArgLoader.java:87)
	at oolloo.jlw.ArgLoader.<init>(ArgLoader.java:16)
	at oolloo.jlw.Wrapper.main(Wrapper.java:22)

### 错误报告、日志与附件

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\���\AppData\Local\Temp\libwrapper-1599703682714437805.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at oolloo.jlw.ArgLoader.loadNative(ArgLoader.java:87)
	at oolloo.jlw.ArgLoader.<init>(ArgLoader.java:16)
	at oolloo.jlw.Wrapper.main(Wrapper.java:22)

**Comment by LBZiXL** [comment]
重装java没用的话，，可以试试重装系统。。

**Comment by RawDiamondMC** [comment]
Java的问题请**不要**放到PCL2反馈区里

**Comment by RawDiamondMC** [comment]
等等，Libwrapper?

**Comment by RawDiamondMC** [comment]
@wdwdwas 用的什么PCL2版本

**Comment by LBZiXL** [comment]
![image](https://user-images.githubusercontent.com/115980764/207600262-20e815f7-118a-4f54-8a34-196aa4352baf.png)

**Comment by RawDiamondMC** [comment]
应当为和#416 重复。。。

**Comment by RawDiamondMC** [comment]
> ![image](https://user-images.githubusercontent.com/115980764/207600262-20e815f7-118a-4f54-8a34-196aa4352baf.png)

因为这个是Javawrapper的问题，在2.4.3（快照版本）修复了，如果还有问题就要问00||00了...
