### ISSUE TITLE
自动安装1.14.4与1.15.2的OptiFabric时使用OptiFabric Origins

### ISSUE THREAD

**Issue by Pixel-Cube** [Hex-Dragon/PCL2#784]
### 检查项

- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未实现这项建议。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Hex-Dragon/PCL2/discussions/categories/%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8/)，确认了这一建议未在投票列表中。

### 描述

自动安装1.14.4和1.15.2版本时，PCL所安装的最新版Fabric不可以和旧版的OptiFabric一起使用，将导致游戏报错。

报错提示：
Uncaught exception in thread "main"
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 6 more
Caused by: java.lang.NoSuchMethodError: net.fabricmc.loader.api.metadata.ModMetadata.getCustomElement(Ljava/lang/String;)Lcom/google/gson/JsonElement;
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:287)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more

建议改成OptiFabric Origins。
具体查看：https://modrinth.com/mod/optifabric-origins

### 原因

按照PCL的安装方式出来的结果将会报错。

**Comment by LTCatt** [comment]
1.14.4 和 1.15.2 的 OptiFabric 最高支持到哪个版本的 Fabric？我需要这个数据来做兼容性检查 =。=

**Comment by Pixel-Cube** [comment]
> 1.14.4 和 1.15.2 的 OptiFabric 最高支持到哪个版本的 Fabric？我需要这个数据来做兼容性检查 =。=

啊...这我还真不知道...

![SHMSCE~C}V}FM~I WL%_A{Y](https://user-images.githubusercontent.com/52479482/210848115-0806737f-2420-4683-bdef-c6acb6b9dfad.png)

发布网站上两个版本写的都是支持使用 Fabric Loader 0.9.x - 0.14.x 运行，但是我试过0.9.x之下的也不能使用。它不仅受fabric影响，可能还受fabric对应的api和optifine版本的影响。

我觉得不如直接关闭这两个版本的OptiFabric下载改成OptiFabric Origins就行了(毕竟其它的fabric版本也用不了

**Comment by LTCatt** [comment]
这是比较头疼的事情……如果要这样折腾，我得额外获取 OptiFabric Origins 的文件列表（每次打开下载页面都会获取），这会增加不少 API 的调用次数。
考虑到 1.14.4 和 1.15.2 都是罕见版本，所以很可能不会支持 OptiFabric Origins 的下载，而是直接在检测到不兼容的时候给出兼容性警报……

**Comment by Pixel-Cube** [comment]
> 这是比较头疼的事情……如果要这样折腾，我得额外获取 OptiFabric Origins 的文件列表（每次打开下载页面都会获取），这会增加不少 API 的调用次数。 考虑到 1.14.4 和 1.15.2 都是罕见版本，所以很可能不会支持 OptiFabric Origins 的下载，而是直接在检测到不兼容的时候给出兼容性警报……

麻烦了...（鞠躬
1.14.4是fabric第一个上线的版本，玩光影之类的还有一部分人在这个版本停着。
当然就算是给个提示也很好了，至少有人再遇到这个问题不会像[那个b站的](https://www.bilibili.com/read/cv18392909)那样不知所措了......

**Comment by LTCatt** [comment]
![image](https://user-images.githubusercontent.com/40348278/211150494-98b2bd39-dc8b-4bf9-9f06-aeebf1e377d3.png)
