### ISSUE TITLE
虚拟机里的MC崩溃

### ISSUE THREAD

**Issue by rongjianuo** [Hex-Dragon/PCL2#989]
### 检查项

- [X] **我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的游戏崩溃不是 PCL2 的原因，请 **不要** 提交反馈。你可以在 QQ 群里或者论坛找人求助，但这里并不是你求助的地方。
- [X] **我已尝试使用其他启动器，其他启动器没有出现问题。** 如果其他启动器也存在问题，证明是游戏本身的问题，并非 PCL2 的问题，请 **不要** 提交反馈。[下载其他启动器](https://www.mcbbs.net/forum.php?mod=forumdisplay&fid=43&filter=typeid&typeid=908)
- [X] 我已点击 `设置 → 启动器 → 检查更新` 确认了启动器已为最新版，且最新版未修复这个 Bug。[怎样更新？](https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-oTgb)
- [X] 我已在 [Issues 页面](https://github.com/Hex-Dragon/PCL2/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

我用虚拟机做局域网测试的时候,崩溃了...（脱了几天）

### 错误报告、日志与附件

[错误报告-1-19-2023_7.14.39_PM.zip](https://github.com/Hex-Dragon/PCL2/files/10476716/-1-19-2023_7.14.39_PM.zip)

**Comment by quannen** [comment]
Failed to verify authentication（无法验证用户
换一个登陆方式试试？
建议你去Discussion提问

**Comment by quannen** [comment]
刻意卡出的Bug龙猫不会修.............

**Comment by WorldHim** [comment]
既然是虚拟机而且你还在调设置而且游戏已经启动，大概率无关 PCL。

**Comment by quannen** [comment]
发一下PCL日志吧

**Comment by rongjianuo** [comment]
里面不是有吗

**Comment by Louis-ZYH** [comment]
这是log文件内关于游戏崩溃的记录：
[18:56:16.772] [Launch] [3284] Minecraft 返回值异常，可能已崩溃
[18:56:16.772] [Launch] [全局] 已无运行中的 Minecraft
[18:56:16.772] [Launch] [3284] Minecraft 已崩溃，将在 2 秒后开始崩溃分析
[18:56:16.820] [UI] 弹出提示：检测到 Minecraft 出现错误，错误分析已开始……
[18:56:17.011] [Launch] [3284] Minecraft 日志监控已退出
[18:56:18.779] [Launch] [3284] 崩溃分析开始
[18:56:18.779] [Crash] 崩溃分析暂存文件夹：C:\Users\WDAGUtilityAccount\AppData\Local\Temp\PCL\CrashAnalyzer\328420548158\
[18:56:18.779] [Crash] 步骤 1：收集日志文件
[18:56:18.779] [Crash] 可能可用的日志文件：C:\Users\WDAGUtilityAccount\Desktop\.minecraft\hs_err_pid2796.log（0.4 分钟）
[18:56:18.779] [Crash] 可能可用的日志文件：C:\Users\WDAGUtilityAccount\Desktop\.minecraft\hs_err_pid3284.log（0 分钟）
[18:56:18.779] [Crash] 可能可用的日志文件：C:\Users\WDAGUtilityAccount\Desktop\.minecraft\logs\latest.log（0.1 分钟）
[18:56:18.784] [Crash] 以下为游戏输出的最后一段内容：
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
[18:56:05] [main/INFO]: Building optimized datafixer
[18:56:13] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:56:14] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:155) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.11.49.jar:?]
	at efu.a(SourceFile:711) [1.19.2.jar:?]
	at efu.<init>(SourceFile:431) [1.19.2.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:205) [1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) [1.19.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.11.49.jar:?]
	... 12 more
[18:56:14] [Render thread/INFO]: Setting user: SB
[18:56:15] [Render thread/WARN]: Skipping bad option: 
[18:56:15] [Render thread/WARN]: Skipping bad option: 
[18:56:15] [Render thread/WARN]: Skipping bad option: 
[18:56:15] [Render thread/WARN]: Skipping bad option: 
[18:56:15] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007f0000000001, pid=3284, tid=6072
#
# JRE version: Java(TM) SE Runtime Environment (17.0.6+9) (build 17.0.6+9-LTS-190)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.6+9-LTS-190, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007f0000000001
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\WDAGUtilityAccount\Desktop\.minecraft\hs_err_pid3284.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
[18:56:18.784] [Crash] 步骤 1：收集日志文件完成，收集到 4 个文件
[18:56:18.784] [Crash] 步骤 2：准备日志文本
[18:56:18.784] [Crash] hs_err_pid2796.log 分类为 HsErr
[18:56:18.784] [Crash] hs_err_pid3284.log 分类为 HsErr
[18:56:18.784] [Crash] latest.log 分类为 MinecraftLog
[18:56:18.784] [Crash] RawOutput.log 分类为 MinecraftLog
[18:56:18.784] [Crash] 输出报告：C:\Users\WDAGUtilityAccount\Desktop\.minecraft\logs\latest.log，作为 Minecraft 或启动器日志
[18:56:18.784] [Crash] 输出报告：C:\Users\WDAGUtilityAccount\AppData\Local\Temp\PCL\CrashAnalyzer\328420548158\RawOutput.log，作为 Minecraft 或启动器日志
[18:56:18.784] [Crash] 导入分析：C:\Users\WDAGUtilityAccount\AppData\Local\Temp\PCL\CrashAnalyzer\328420548158\RawOutput.log，作为启动器日志
[18:56:18.784] [Crash] 导入分析：C:\Users\WDAGUtilityAccount\Desktop\.minecraft\logs\latest.log，作为 Minecraft 日志
[18:56:18.784] [Crash] 输出报告：C:\Users\WDAGUtilityAccount\Desktop\.minecraft\hs_err_pid3284.log，作为虚拟机错误信息
[18:56:18.784] [Crash] 导入分析：C:\Users\WDAGUtilityAccount\Desktop\.minecraft\hs_err_pid3284.log，作为虚拟机错误信息
[18:56:18.784] [Crash] 步骤 2：准备日志文本完成，找到游戏日志、虚拟机日志用作分析
[18:56:18.784] [Crash] 步骤 3：分析崩溃原因
[18:56:18.784] [Crash] 可能并未安装 Mod，不进行堆栈分析
[18:56:18.784] [Crash] 步骤 3：分析崩溃原因完成，未找到可能的原因
[18:56:18.811] [System] 窗口已置顶，位置：(192, 27.2), 830.4 x 520
[18:56:18.815] [Control] 普通弹窗：Minecraft 出现错误
很抱歉，你的游戏出现了一些问题……
如果要寻求帮助，请向他人发送错误报告文件，而不是发送这个窗口的截图。
你也可以查看错误报告，其中可能会有出错的原因。

**Comment by youzi-2333** [comment]
> com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401

说明服务器返回http状态码401，你的账号密码不对吗（？）

**Comment by rongjianuo** [comment]
我没用正版
用的离线
就一个正版

**Comment by rongjianuo** [comment]
不知道

**Comment by youzi-2333** [comment]
那就先等龙猫修吧……

**Comment by LTCatt** [comment]
即使是离线 MC 依然会尝试获取皮肤信息。
这个问题与启动器无关。

**Comment by youzi-2333** [comment]
？mc崩溃关皮肤啥事……



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月27日 16:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hex-Dragon/PCL2] 虚拟机里的MC崩溃 (Issue #989) |

即使是离线 MC 依然会尝试获取皮肤信息。
这个问题与启动器无关。
